INSERT INTO vertical_configs (vertical, display_name, bizdev_search_queries, bizdev_lead_scoring_criteria, bizdev_system_prompt, outreach_system_prompt, outreach_message_templates, outreach_hinglish_phrases, followup_system_prompt, followup_message_templates, proposal_system_prompt, proposal_section_structure, proposal_value_props, retention_system_prompt, retention_checkin_templates, reporter_metrics_to_highlight, website_system_prompt, website_default_pages, website_default_color_scheme)
VALUES 
('restaurant', 'Restaurant', 
  '["restaurants in {city} without website", "new restaurants {city} Google Maps"]'::jsonb,
  '{"has_website": 10, "has_google_reviews": 5}'::jsonb,
  'You are finding restaurants in {city} without online presence.',
  'Write Hinglish outreach for restaurant owners.',
  '[{"subject": "Your restaurant website", "body": "Namaste {business_name}..."}]'::jsonb,
  '["order abhi bhi phone se lete ho?", "website banao aur orders double karo"]'::jsonb,
  'Follow up with restaurant leads about website.',
  '[{"template": "Just checking if you saw my last message..."}]'::jsonb,
  'Create proposal for restaurant website with online menu.',
  '{"sections": ["Online Menu", "WhatsApp Ordering", "Google Maps"]}'::jsonb,
  '{"prop1": "24 hour delivery", "prop2": "WhatsApp integration"}'::jsonb,
  'Check in with restaurant clients about their website performance.',
  '[{"day": 30, "template": "How is your website performing?"}]'::jsonb,
  '["website_views", "orders_received"]'::jsonb,
  'Build website for Indian restaurant with online menu and WhatsApp ordering.',
  '{"pages": ["home", "menu", "contact"]}'::jsonb,
  '{"primary": "#dc2626", "accent": "#f59e0b"}'::jsonb
),
('clinic', 'Clinic', 
  '["clinics in {city} without website", "doctors in {city} low Google reviews"]'::jsonb,
  '{"has_website": 10, "has_google_reviews": 5}'::jsonb,
  'You are finding clinics in {city} needing digital presence.',
  'Write Hinglish outreach for clinic owners.',
  '[{"subject": "Your clinic needs patients", "body": "Namaste Doctor..."}]'::jsonb,
  '["appointment bookings abhi bhi phone pe?", "patients ko recall karna mushkil hai?"]'::jsonb,
  'Follow up with clinic leads about appointment system.',
  '[{"template": "Just checking about your clinic website..."}]'::jsonb,
  'Create proposal for clinic website with appointment booking.',
  '{"sections": ["Services", "Appointment Booking", "Doctor Profile"]}'::jsonb,
  '{"prop1": "Patient recall system", "prop2": "WhatsApp reminders"}'::jsonb,
  'Check in with clinic clients about patient engagement.',
  '[{"day": 30, "template": "How many appointments booked online?"}]'::jsonb,
  '["appointments_booked", "patient_messages"]'::jsonb,
  'Build website for Indian clinic with appointment booking and WhatsApp.',
  '{"pages": ["home", "services", "appointment"]}'::jsonb,
  '{"primary": "#2563eb", "accent": "#10b981"}'::jsonb
);
