export const CITIES = [
  'Mumbai',
  'Delhi',
  'Bangalore',
  'Hyderabad',
  'Chennai',
  'Kolkata',
  'Pune',
  'Ahmedabad',
  'Jaipur',
  'Surat',
  'Lucknow',
  'Kanpur',
  'Nagpur',
  'Indore',
  'Thane',
  'Bhopal',
  'Visakhapatnam',
  'Pimpri-Chinchwad',
  'Patna',
  'Vadodara',
  'Ghaziabad',
  'Ludhiana',
  'Agra',
  'Nashik',
  'Faridabad',
  'Meerut',
  'Rajkot',
  'Kalyan-Dombivali',
  'Vasai-Virar',
  'Varanasi',
  'Srinagar',
  'Aurangabad',
  'Dhanbad',
  'Amritsar',
  'Navi Mumbai',
  'Allahabad',
  'Howrah',
  'Coimbatore',
]

export const CATEGORIES = [
  'restaurant',
  'cafe',
  'bakery',
  'cake shop',
  'catering',
  'cloud kitchen',
  'sweet shop',
  'clinic',
  'hospital',
  'dental clinic',
  'pharmacy',
  'diagnostic centre',
  'physiotherapy',
  'ayurveda clinic',
  'homeopathy clinic',
  'school',
  'college',
  'coaching centre',
  'tuition centre',
  'yoga studio',
  'dance academy',
  'music academy',
  'gym',
  'fitness centre',
  'salon',
  'beauty parlour',
  'spa',
  'nail studio',
  'boutique',
  'clothing store',
  'jeweler',
  'footwear store',
  'electronics shop',
  'mobile shop',
  'computer repair',
  'furniture store',
  'home decor',
  'interior designer',
  'supermarket',
  'grocery store',
  'hotel',
  'guest house',
  'travel agency',
  'car service',
  'driving school',
  'real estate',
  'property dealer',
  'architect',
  'event planner',
  'wedding planner',
  'photographer',
  'videographer',
  'printing shop',
  'digital marketing',
  'graphic designer',
  'chartered accountant',
  'lawyer',
  'insurance agent',
  'loan agent',
  'construction company',
  'hardware store',
  'electrical shop',
  'pest control',
]
