'use client';

import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Search, ExternalLink, RefreshCw, MessageCircle, AlertCircle, Loader2, Gauge, Flame, ArrowUpRight } from 'lucide-react';

interface SocialPost {
    id: string;
    title: string;
    text: string;
    link: string;
    author: string;
    platform: 'Reddit' | 'HackerNews' | 'Twitter';
    score: number;
    createdAt: string;
    intentScore: number;
}

import AddToCampaignModal from '@/components/admin/growth/AddToCampaignModal';

export default function SocialMonitorPage() {
    const [query, setQuery] = useState('hiring developer');
    const [posts, setPosts] = useState<SocialPost[]>([]);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [savedKeywords, setSavedKeywords] = useState<string[]>([]);
    const [selectedLead, setSelectedLead] = useState<{ name: string, source: string, source_id: string } | null>(null);
    const [selectedPosts, setSelectedPosts] = useState<string[]>([]);
    const [isBulkAdding, setIsBulkAdding] = useState(false);

    const fetchPosts = async (searchQuery: string = query) => {
        setIsLoading(true);
        setError(null);
        setPosts([]); // Clear
        try {
            const res = await fetch(`/api/admin/growth/social?q=${encodeURIComponent(searchQuery)}`);
            if (!res.ok) throw new Error(`HTTP Error: ${res.status} ${res.statusText}`);
            if (!res.body) throw new Error('No response body');

            const reader = res.body.getReader();
            const decoder = new TextDecoder();
            let buffer = '';

            while (true) {
                const { done, value } = await reader.read();
                if (done) break;

                buffer += decoder.decode(value, { stream: true });
                const lines = buffer.split('\n');
                buffer = lines.pop() || '';

                for (const line of lines) {
                    if (!line.trim()) continue;
                    try {
                        const newPosts = JSON.parse(line);
                        if (newPosts.error) {
                            console.error('Stream error:', newPosts.error);
                            setError(newPosts.error); // Show error to user
                        } else if (Array.isArray(newPosts)) {
                            setPosts(prev => {
                                const existingIds = new Set(prev.map(p => p.id));
                                const uniqueNew = newPosts.filter(p => !existingIds.has(p.id));
                                return [...prev, ...uniqueNew];
                            });
                        }
                    } catch (e) {
                        console.error('JSON parse error', e);
                        // Don't error on one bad line, just log
                    }
                }
            }
        } catch (error: any) {
            console.error('Failed to fetch posts', error);
            setError(error.message || 'Failed to connect to server');
        } finally {
            setIsLoading(false);
        }
    };

    const toggleSelectPost = (id: string) => {
        if (selectedPosts.includes(id)) {
            setSelectedPosts(selectedPosts.filter(p => p !== id));
        } else {
            setSelectedPosts([...selectedPosts, id]);
        }
    };

    const handleBulkAdd = async () => {
        if (selectedPosts.length === 0) return;
        setIsBulkAdding(true);

        // Find full post objects
        const leadsToAdd = posts.filter(p => selectedPosts.includes(p.id)).map(p => ({
            name: p.author,
            source: p.platform,
            source_id: p.id,
            // Email will be generated by API as placeholder
        }));

        try {
            const res = await fetch('/api/admin/growth/leads/bulk-add', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ leads: leadsToAdd })
            });
            const data = await res.json();
            if (data.success) {
                alert(`Successfully added ${data.count} leads to database!`);
                setSelectedPosts([]);
            } else {
                alert('Failed to add leads: ' + data.error);
            }
        } catch (error) {
            console.error(error);
            alert('An error occurred.');
        } finally {
            setIsBulkAdding(false);
        }
    };

    const handleOneClickAdd = async (post: SocialPost) => {
        // Optimistic UI could be added here
        try {
            const res = await fetch('/api/admin/growth/leads/bulk-add', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    leads: [{
                        name: post.author,
                        source: post.platform,
                        source_id: post.id
                    }]
                })
            });
            const data = await res.json();
            if (data.success) {
                // Toast or small notification would be better, but alert for now
                alert(`Added ${post.author} to Leads Database.`);
            } else {
                alert('Failed: ' + data.error);
            }
        } catch (error) {
            console.error(error);
        }
    };

    useEffect(() => {
        // Load saved keywords from local storage
        const saved = localStorage.getItem('growth_keywords');
        if (saved) {
            setSavedKeywords(JSON.parse(saved));
        }
        fetchPosts();
    }, []);

    const handleSearch = (e: React.FormEvent) => {
        e.preventDefault();
        fetchPosts();
    };

    const toggleSaveKeyword = () => {
        let newKeywords;
        if (savedKeywords.includes(query)) {
            newKeywords = savedKeywords.filter(k => k !== query);
        } else {
            newKeywords = [...savedKeywords, query];
        }
        setSavedKeywords(newKeywords);
        localStorage.setItem('growth_keywords', JSON.stringify(newKeywords));
    };

    const handleKeywordClick = (k: string) => {
        setQuery(k);
        fetchPosts(k);
    };

    return (
        <div className="p-8 max-w-7xl mx-auto min-h-screen space-y-8">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                <div>
                    <h1 className="text-3xl font-bold flex items-center gap-3">
                        <MessageCircle className="w-8 h-8 text-orange-500" />
                        Social Monitor
                    </h1>
                    <p className="text-[var(--muted)] mt-1">
                        AI-powered listening on Reddit.
                    </p>
                </div>
                <div className="flex gap-2">
                    {selectedPosts.length > 0 && (
                        <button
                            onClick={handleBulkAdd}
                            disabled={isBulkAdding}
                            className="px-4 py-2 rounded-lg bg-green-600 text-white hover:bg-green-700 transition-colors flex items-center gap-2 font-bold animate-in fade-in slide-in-from-bottom-2"
                        >
                            {isBulkAdding ? <Loader2 className="w-4 h-4 animate-spin" /> : <div className="flex items-center justify-center w-5 h-5 rounded-full bg-white text-green-600 text-xs">{selectedPosts.length}</div>}
                            Add Selected to DB
                        </button>
                    )}
                    <button
                        onClick={() => fetchPosts()}
                        disabled={isLoading}
                        className="p-2 rounded-lg bg-[var(--surface)] border border-[var(--border)] hover:bg-[var(--secondary)] transition-colors"
                    >
                        <RefreshCw className={`w-5 h-5 ${isLoading ? 'animate-spin' : ''}`} />
                    </button>
                </div>
            </div>

            {/* Search */}
            <div className="glass-card p-4 space-y-4">
                <div className="flex flex-col md:flex-row gap-4">
                    <form onSubmit={handleSearch} className="flex-1 flex gap-2">
                        <div className="relative flex-1">
                            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-[var(--muted)]" />
                            <input
                                type="text"
                                value={query}
                                onChange={(e) => setQuery(e.target.value)}
                                placeholder="Monitor keywords..."
                                className="w-full pl-10 pr-4 py-2 rounded-xl bg-[var(--background)] border border-[var(--border)] focus:ring-2 focus:ring-[var(--primary)] outline-none"
                            />
                        </div>
                        <button
                            type="submit"
                            disabled={isLoading}
                            className="px-6 py-2 bg-[var(--primary)] text-white rounded-xl hover:bg-blue-600 transition-colors font-medium"
                        >
                            Monitor
                        </button>
                        <button
                            type="button"
                            onClick={toggleSaveKeyword}
                            className={`px-4 py-2 rounded-xl border border-[var(--border)] transition-colors ${savedKeywords.includes(query) ? 'bg-orange-500/10 text-orange-500' : 'hover:bg-[var(--secondary)]'
                                }`}
                            title={savedKeywords.includes(query) ? "Remove saved keyword" : "Save keyword"}
                        >
                            {savedKeywords.includes(query) ? 'Saved' : 'Save'}
                        </button>
                    </form>
                </div>

                {/* Saved Keywords Chips */}
                {savedKeywords.length > 0 && (
                    <div className="flex flex-wrap gap-2">
                        <span className="text-sm text-[var(--muted)] py-1">Saved:</span>
                        {savedKeywords.map(k => (
                            <button
                                key={k}
                                onClick={() => handleKeywordClick(k)}
                                className={`px-3 py-1 rounded-full text-xs font-medium border transition-colors ${query === k
                                    ? 'bg-[var(--primary)] text-white border-[var(--primary)]'
                                    : 'bg-[var(--surface)] text-[var(--muted)] border-[var(--border)] hover:border-[var(--primary)]'
                                    }`}
                            >
                                {k}
                            </button>
                        ))}
                    </div>
                )}
            </div>

            {/* Results */}
            <div className="grid gap-4">
                {error && (
                    <div className="p-4 rounded-xl bg-red-500/10 border border-red-500/20 text-red-500 flex items-center gap-3 animate-in slide-in-from-top-2">
                        <AlertCircle className="w-5 h-5 shrink-0" />
                        <p className="font-medium text-sm">{error}</p>
                    </div>
                )}

                {isLoading ? (
                    <div className="py-20 text-center">
                        <Loader2 className="w-10 h-10 animate-spin mx-auto mb-4 text-[var(--primary)]" />
                        <p className="text-[var(--muted)]">Analyzing social signals across platforms...<br /><span className="text-xs opacity-50">(Check server logs if this persists)</span></p>
                    </div>
                ) : posts.length === 0 ? (
                    <div className="py-20 text-center glass-card">
                        <MessageCircle className="w-12 h-12 mx-auto mb-4 text-[var(--muted)] opacity-50" />
                        <h3 className="text-lg font-bold mb-1">No signals found</h3>
                        <p className="text-[var(--muted)]">Try broadening your keywords.</p>
                    </div>
                ) : (
                    <div className="space-y-4">
                        {posts.map((post, index) => (
                            <motion.div
                                key={post.id}
                                initial={{ opacity: 0, y: 10 }}
                                animate={{ opacity: 1, y: 0, transition: { delay: index * 0.05 } }}
                                className={`glass-card p-6 border-l-4 transition-all hover:shadow-lg relative group ${post.intentScore >= 7
                                    ? 'border-l-green-500 bg-green-500/5'
                                    : post.intentScore >= 4
                                        ? 'border-l-yellow-500'
                                        : 'border-l-transparent'
                                    } ${selectedPosts.includes(post.id) ? 'ring-2 ring-[var(--primary)] bg-[var(--primary)]/5' : ''}`}
                            >
                                <div className="flex justify-between items-start gap-4">
                                    {/* Checkbox */}
                                    <div className="pt-1">
                                        <input
                                            type="checkbox"
                                            checked={selectedPosts.includes(post.id)}
                                            onChange={() => toggleSelectPost(post.id)}
                                            className="w-5 h-5 rounded border-gray-300 text-[var(--primary)] focus:ring-[var(--primary)] cursor-pointer"
                                        />
                                    </div>

                                    <div className="flex-1">
                                        <div className="flex items-center gap-2 mb-2">
                                            {/* Platform Badge */}
                                            <span className={`px-2 py-0.5 rounded text-xs font-bold flex items-center gap-1 ${post.platform === 'Reddit'
                                                ? 'bg-orange-500/10 text-orange-500'
                                                : 'bg-orange-600/10 text-orange-600' // HN Color
                                                }`}>
                                                {post.platform}
                                            </span>

                                            <span className="text-xs text-[var(--muted)]">Posted by {post.author} • {new Date(post.createdAt).toLocaleDateString()}</span>

                                            {/* Intent Badge */}
                                            {post.intentScore >= 5 && (
                                                <span className="px-2 py-0.5 rounded text-xs font-bold bg-green-500/10 text-green-500 flex items-center gap-1 animate-pulse">
                                                    <Flame className="w-3 h-3" /> High Intent
                                                </span>
                                            )}
                                        </div>

                                        <h3 className="font-bold text-lg mb-2">{post.title}</h3>

                                        {/* Snippet with basic sanitization */}
                                        <p className="text-sm text-[var(--muted)] line-clamp-3 mb-4 font-mono bg-[var(--background)] p-3 rounded-lg border border-[var(--border)] opacity-80">
                                            {post.text || 'No content preview available.'}
                                        </p>

                                        <div className="flex items-center gap-4">
                                            <span className="text-xs font-medium flex items-center gap-1 bg-[var(--secondary)] px-2 py-1 rounded">
                                                <ArrowUpRight className="w-3 h-3" /> Score: {post.score}
                                            </span>
                                            <span className="text-xs font-medium flex items-center gap-1 bg-[var(--secondary)] px-2 py-1 rounded" title="AI Calculated Intent Score">
                                                <Gauge className="w-3 h-3" /> Intent: {post.intentScore}/10
                                            </span>
                                        </div>
                                    </div>

                                    <div className="flex flex-col gap-2">
                                        <button
                                            onClick={() => handleOneClickAdd(post)}
                                            className="p-3 rounded-xl bg-[var(--surface)] text-[var(--foreground)] border border-[var(--border)] hover:bg-green-600 hover:text-white hover:border-green-600 transition-colors whitespace-nowrap text-xs font-bold flex items-center justify-center gap-1"
                                            title="Add directly to leads database"
                                        >
                                            <span className="text-lg leading-none">+</span> One Click Add
                                        </button>
                                        <button
                                            onClick={() => setSelectedLead({ name: 'User: ' + post.author, source: post.platform, source_id: post.id })}
                                            className="px-3 py-1 rounded text-[var(--muted)] hover:text-[var(--foreground)] text-[10px] font-medium"
                                        >
                                            Manual Entry
                                        </button>

                                        {post.platform === 'Reddit' && (
                                            <DraftReplyButton post={post} />
                                        )}

                                        <a
                                            href={post.link}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="p-3 rounded-xl bg-[var(--primary)] text-white hover:bg-blue-600 transition-colors shadow-lg shadow-blue-500/20 flex justify-center"
                                        >
                                            <ExternalLink className="w-5 h-5" />
                                        </a>
                                    </div>
                                </div>
                            </motion.div>
                        ))}
                    </div>
                )}
            </div>

            <AddToCampaignModal
                isOpen={!!selectedLead}
                onClose={() => setSelectedLead(null)}
                leadData={selectedLead}
            />
        </div>
    );
}

function DraftReplyButton({ post }: { post: SocialPost }) {
    const [isLoading, setIsLoading] = useState(false);

    const handleDraft = async () => {
        setIsLoading(true);
        try {
            const res = await fetch('/api/admin/growth/social/draft', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ post }),
            });
            const data = await res.json();

            if (data.success && data.draft) {
                const url = `https://www.reddit.com/message/compose?to=${post.author}&subject=${encodeURIComponent(data.subject)}&message=${encodeURIComponent(data.draft)}`;
                window.open(url, '_blank');
            } else {
                alert(`Failed: ${data.error || 'Unknown error'}`);
            }
        } catch (e: any) {
            console.error(e);
            alert(`Error: ${e.message}`);
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <button
            onClick={handleDraft}
            disabled={isLoading}
            className="p-3 rounded-xl bg-[#ff4500]/10 text-[#ff4500] border border-[#ff4500]/20 hover:bg-[#ff4500]/20 transition-colors whitespace-nowrap text-xs font-bold flex items-center justify-center gap-2"
        >
            {isLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <MessageCircle className="w-4 h-4" />}
            {isLoading ? 'Drafting...' : 'Draft Message'}
        </button>
    );
}
