export type SectionType =
  | 'hero' | 'about' | 'features' | 'menu' | 'gallery'
  | 'testimonials' | 'contact' | 'hours' | 'cta' | 'team'
  | 'pricing' | 'stats' | 'faq' | 'blog'

export interface Section {
  id: string
  type: SectionType
  label: string
  enabled: boolean
  content: Record<string, string | string[]>
}

export interface ColorTheme {
  id: string
  label: string
  primary: string
  secondary: string
  accent: string
  bg: string
  text: string
  preview: [string, string, string]
}

export interface FontPair {
  id: string
  label?: string
  heading: string
  body: string
  headingClass: string
  bodyClass: string
}

export interface Template {
  id: string
  label: string
  category: string
  emoji: string
  description: string
  defaultSections: Section[]
  suggestedThemes: string[]
}

export const COLOR_THEMES: ColorTheme[] = [
  { id: 'espresso', label: 'Espresso', primary: '#3B1F0A', secondary: '#6F4E37', accent: '#C9A27E', bg: '#FDF8F3', text: '#1a0f05', preview: ['#3B1F0A', '#6F4E37', '#C9A27E'] },
  { id: 'ocean', label: 'Ocean', primary: '#0A4D68', secondary: '#088395', accent: '#05BFDB', bg: '#F0FBFF', text: '#011c26', preview: ['#0A4D68', '#088395', '#05BFDB'] },
  { id: 'forest', label: 'Forest', primary: '#1A3A2A', secondary: '#2D6A4F', accent: '#52B788', bg: '#F5FBF7', text: '#0a1a12', preview: ['#1A3A2A', '#2D6A4F', '#52B788'] },
  { id: 'rose', label: 'Rose', primary: '#6B1C2A', secondary: '#A84455', accent: '#E8748A', bg: '#FFF5F7', text: '#2d0a12', preview: ['#6B1C2A', '#A84455', '#E8748A'] },
  { id: 'slate', label: 'Slate', primary: '#1E293B', secondary: '#334155', accent: '#3B82F6', bg: '#F8FAFC', text: '#0f172a', preview: ['#1E293B', '#334155', '#3B82F6'] },
  { id: 'golden', label: 'Golden', primary: '#78350F', secondary: '#B45309', accent: '#F59E0B', bg: '#FFFBEB', text: '#1c0a02', preview: ['#78350F', '#B45309', '#F59E0B'] },
  { id: 'violet', label: 'Violet', primary: '#3B0764', secondary: '#6D28D9', accent: '#A78BFA', bg: '#F5F3FF', text: '#1a0332', preview: ['#3B0764', '#6D28D9', '#A78BFA'] },
  { id: 'midnight', label: 'Midnight', primary: '#0F172A', secondary: '#1E293B', accent: '#38BDF8', bg: '#F0F9FF', text: '#020617', preview: ['#0F172A', '#1E293B', '#38BDF8'] },
  { id: 'terracotta', label: 'Terracotta', primary: '#7C2D12', secondary: '#C2410C', accent: '#FB923C', bg: '#FFF7ED', text: '#431407', preview: ['#7C2D12', '#C2410C', '#FB923C'] },
  { id: 'sage', label: 'Sage', primary: '#1D3016', secondary: '#365526', accent: '#86EFAC', bg: '#F0FDF4', text: '#052e16', preview: ['#1D3016', '#365526', '#86EFAC'] },
  { id: 'coral', label: 'Coral', primary: '#9B2335', secondary: '#C0392B', accent: '#F1948A', bg: '#FEF5F5', text: '#2c0a0a', preview: ['#9B2335', '#C0392B', '#F1948A'] },
  { id: 'navy', label: 'Navy Royal', primary: '#0B1F4C', secondary: '#1A3770', accent: '#4A90E2', bg: '#F0F5FF', text: '#060f26', preview: ['#0B1F4C', '#1A3770', '#4A90E2'] },
  { id: 'copper', label: 'Copper', primary: '#6D3B2E', secondary: '#B5451B', accent: '#E8A87C', bg: '#FDF5F0', text: '#2d1510', preview: ['#6D3B2E', '#B5451B', '#E8A87C'] },
  { id: 'emerald_deep', label: 'Deep Emerald', primary: '#064E3B', secondary: '#065F46', accent: '#34D399', bg: '#ECFDF5', text: '#022c22', preview: ['#064E3B', '#065F46', '#34D399'] },
  { id: 'plum', label: 'Plum', primary: '#4A1942', secondary: '#7B2D8B', accent: '#C084FC', bg: '#FAF5FF', text: '#1e0a1e', preview: ['#4A1942', '#7B2D8B', '#C084FC'] },
  { id: 'charcoal', label: 'Charcoal', primary: '#1C1C1E', secondary: '#2C2C2E', accent: '#FF9F0A', bg: '#F9F9F9', text: '#0a0a0a', preview: ['#1C1C1E', '#2C2C2E', '#FF9F0A'] },
  { id: 'teal_fresh', label: 'Fresh Teal', primary: '#0D5C63', secondary: '#17838C', accent: '#56CFD2', bg: '#F0FCFD', text: '#022e31', preview: ['#0D5C63', '#17838C', '#56CFD2'] },
  { id: 'burgundy', label: 'Burgundy', primary: '#4A0E2A', secondary: '#7A1C4B', accent: '#E8829B', bg: '#FDF5F8', text: '#1e0412', preview: ['#4A0E2A', '#7A1C4B', '#E8829B'] },
  { id: 'olive', label: 'Olive Grove', primary: '#3D4A1E', secondary: '#5C6F2E', accent: '#B5CC6F', bg: '#F8FAF0', text: '#1a2008', preview: ['#3D4A1E', '#5C6F2E', '#B5CC6F'] },
  { id: 'indigo_warm', label: 'Warm Indigo', primary: '#2D3189', secondary: '#4A4FC4', accent: '#818CF8', bg: '#F5F5FF', text: '#12143d', preview: ['#2D3189', '#4A4FC4', '#818CF8'] },
]

export const FONT_PAIRS: FontPair[] = [
  { id: 'modern', label: 'Modern Clean', heading: 'Inter', body: 'Inter', headingClass: 'font-sans font-bold', bodyClass: 'font-sans' },
  { id: 'elegant', label: 'Elegant Serif', heading: 'Playfair Display', body: 'Lato', headingClass: 'font-serif font-bold', bodyClass: 'font-sans' },
  { id: 'warm', label: 'Warm & Friendly', heading: 'Poppins', body: 'Nunito', headingClass: 'font-sans font-semibold', bodyClass: 'font-sans' },
  { id: 'classic', label: 'Classic Editorial', heading: 'Merriweather', body: 'Source Sans Pro', headingClass: 'font-serif font-bold', bodyClass: 'font-sans' },
  { id: 'minimal', label: 'Minimal Swiss', heading: 'DM Sans', body: 'DM Sans', headingClass: 'font-sans font-medium tracking-tight', bodyClass: 'font-sans' },
  { id: 'editorial', label: 'Editorial Bold', heading: 'Fraunces', body: 'Libre Baskerville', headingClass: 'font-serif font-black', bodyClass: 'font-serif' },
  { id: 'techy', label: 'Techy', heading: 'Space Grotesk', body: 'IBM Plex Mono', headingClass: 'font-sans font-semibold tracking-tight', bodyClass: 'font-mono' },
  { id: 'playful', label: 'Playful', heading: 'Nunito', body: 'Nunito', headingClass: 'font-sans font-extrabold', bodyClass: 'font-sans' },
  { id: 'luxury', label: 'Luxury', heading: 'Cormorant Garamond', body: 'Raleway', headingClass: 'font-serif font-light tracking-wider', bodyClass: 'font-sans' },
  { id: 'humanist', label: 'Humanist', heading: 'Nunito Sans', body: 'Lora', headingClass: 'font-sans font-bold', bodyClass: 'font-serif' },
  { id: 'crimson', label: 'Crimson Classic', heading: 'Crimson Text', body: 'Source Sans 3', headingClass: 'font-serif font-semibold', bodyClass: 'font-sans' },
  { id: 'josefin', label: 'Josefin Geometric', heading: 'Josefin Sans', body: 'Josefin Slab', headingClass: 'font-sans font-bold tracking-wide uppercase', bodyClass: 'font-serif' },
  { id: 'cairo', label: 'Cairo Bold', heading: 'Cairo', body: 'Cairo', headingClass: 'font-sans font-extrabold', bodyClass: 'font-sans' },
  { id: 'outfit', label: 'Outfit Modern', heading: 'Outfit', body: 'Outfit', headingClass: 'font-sans font-black tracking-tight', bodyClass: 'font-sans font-light' },
  { id: 'syne', label: 'Syne Futuristic', heading: 'Syne', body: 'Syne', headingClass: 'font-sans font-extrabold tracking-tighter', bodyClass: 'font-sans' },
]

export const TEMPLATES: Template[] = [
  {
    id: 'cafe',
    label: 'Café',
    category: 'Food & Beverage',
    emoji: '☕',
    description: 'Perfect for cafés, coffee shops, and tea houses',
    suggestedThemes: ['espresso', 'golden', 'terracotta'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Your Perfect Cup, Every Morning', subtext: 'Fresh brews, cozy vibes, and artisanal pastries — all in the heart of [City]', cta: 'Order Now', ctaLink: '#order' } },
      { id: 'about', type: 'about', label: 'Our Story', enabled: true, content: { title: 'Crafted with Love Since 2018', body: 'What started as a small corner café has grown into a beloved community gathering spot. We source our beans directly from small farms in Coorg and Chikmagalur.', image: '' } },
      { id: 'menu', type: 'menu', label: 'Menu', enabled: true, content: { title: 'Our Menu', categories: ['Hot Drinks', 'Cold Brews', 'Pastries', 'Breakfast'] } },
      { id: 'gallery', type: 'gallery', label: 'Gallery', enabled: true, content: { title: 'Inside Our Café' } },
      { id: 'hours', type: 'hours', label: 'Hours & Location', enabled: true, content: { weekdays: 'Mon–Fri: 7:00 AM – 9:00 PM', weekends: 'Sat–Sun: 8:00 AM – 10:00 PM', address: '42 MG Road, Bengaluru 560001', phone: '+91 98765 43210', maps: '' } },
      { id: 'testimonials', type: 'testimonials', label: 'Reviews', enabled: true, content: { title: 'What Our Regulars Say' } },
      { id: 'contact', type: 'contact', label: 'Contact', enabled: true, content: { title: 'Get in Touch', email: 'hello@yourcafe.in' } },
    ],
  },
  {
    id: 'restaurant',
    label: 'Restaurant',
    category: 'Food & Beverage',
    emoji: '🍽️',
    description: 'Full-service restaurants, dhabas, and fine dining',
    suggestedThemes: ['terracotta', 'golden', 'rose'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'An Unforgettable Dining Experience', subtext: 'Authentic flavors, warm hospitality, and memories that last a lifetime', cta: 'Reserve a Table', ctaLink: '#reserve' } },
      { id: 'about', type: 'about', label: 'About Us', enabled: true, content: { title: 'Our Culinary Story', body: 'Three generations of family recipes, reimagined for the modern palate. Every dish tells a story of tradition, passion, and the finest local ingredients.' } },
      { id: 'menu', type: 'menu', label: 'Our Menu', enabled: true, content: { title: 'Signature Dishes', categories: ['Starters', 'Mains', 'Breads', 'Desserts', 'Beverages'] } },
      { id: 'stats', type: 'stats', label: 'Stats', enabled: true, content: { stats: ['15+ Years Serving', '200+ Happy Tables/Day', '50+ Signature Dishes', '4.8★ on Zomato'] } },
      { id: 'gallery', type: 'gallery', label: 'Food Gallery', enabled: true, content: { title: 'Feast Your Eyes' } },
      { id: 'testimonials', type: 'testimonials', label: 'Guest Reviews', enabled: true, content: { title: 'What Our Guests Say' } },
      { id: 'hours', type: 'hours', label: 'Reservations & Hours', enabled: true, content: { weekdays: 'Tue–Sun: 12:00 PM – 11:00 PM', weekends: 'Monday: Closed', address: '7 Residency Road, Bengaluru', phone: '+91 98765 43210' } },
      { id: 'contact', type: 'contact', label: 'Contact', enabled: true, content: { title: 'Make a Reservation', email: 'reserve@restaurant.in' } },
    ],
  },
  {
    id: 'bookstore',
    label: 'Bookstore',
    category: 'Retail',
    emoji: '📚',
    description: 'Independent bookstores, libraries, and reading cafés',
    suggestedThemes: ['slate', 'forest', 'violet'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero', enabled: true, content: { headline: 'Every Page, A New World', subtext: 'Curated collections, rare finds, and a community of passionate readers', cta: 'Browse Our Collection', ctaLink: '#books' } },
      { id: 'features', type: 'features', label: 'What We Offer', enabled: true, content: { title: 'More Than Just Books', items: ['Curated New Arrivals', 'Rare & Antiquarian Books', 'Author Events', 'Reading Club', 'Gift Wrapping', 'Custom Recommendations'] } },
      { id: 'menu', type: 'menu', label: 'Collections', enabled: true, content: { title: 'Browse by Genre', categories: ['Fiction', 'Non-Fiction', 'Children\'s', 'Academic', 'Comics', 'Rare Books'] } },
      { id: 'testimonials', type: 'testimonials', label: 'Reader Reviews', enabled: true, content: { title: 'From Our Reading Community' } },
      { id: 'blog', type: 'blog', label: 'Reading List', enabled: true, content: { title: 'Our Latest Recommendations' } },
      { id: 'hours', type: 'hours', label: 'Visit Us', enabled: true, content: { weekdays: 'Mon–Sat: 10:00 AM – 8:00 PM', weekends: 'Sunday: 11:00 AM – 6:00 PM', address: '3 Church Street, Bengaluru', phone: '+91 80 2222 3333' } },
      { id: 'contact', type: 'contact', label: 'Contact', enabled: true, content: { title: 'Have a Question?', email: 'books@yourbookstore.in' } },
    ],
  },
  {
    id: 'salon',
    label: 'Salon & Spa',
    category: 'Beauty & Wellness',
    emoji: '💆',
    description: 'Hair salons, beauty parlors, and wellness spas',
    suggestedThemes: ['rose', 'sage', 'golden'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero', enabled: true, content: { headline: 'Look Good. Feel Amazing.', subtext: 'Expert stylists, premium products, and a sanctuary of calm — just for you', cta: 'Book Appointment', ctaLink: '#book' } },
      { id: 'features', type: 'features', label: 'Our Services', enabled: true, content: { title: 'What We Offer', items: ['Hair Styling & Cuts', 'Bridal Packages', 'Facials & Skin Care', 'Massage Therapy', 'Nail Art', 'Hair Color & Treatment'] } },
      { id: 'team', type: 'team', label: 'Our Team', enabled: true, content: { title: 'Meet Our Expert Stylists' } },
      { id: 'pricing', type: 'pricing', label: 'Price List', enabled: true, content: { title: 'Transparent Pricing' } },
      { id: 'gallery', type: 'gallery', label: 'Portfolio', enabled: true, content: { title: 'Our Work' } },
      { id: 'testimonials', type: 'testimonials', label: 'Client Reviews', enabled: true, content: { title: 'Happy Clients' } },
      { id: 'contact', type: 'contact', label: 'Book Now', enabled: true, content: { title: 'Schedule Your Visit', email: 'appointments@salon.in' } },
    ],
  },
  {
    id: 'gym',
    label: 'Gym & Fitness',
    category: 'Health & Fitness',
    emoji: '🏋️',
    description: 'Gyms, yoga studios, and fitness centers',
    suggestedThemes: ['midnight', 'slate', 'forest'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero', enabled: true, content: { headline: 'Transform Your Body. Transform Your Life.', subtext: 'State-of-the-art equipment, expert trainers, and a community that pushes you further', cta: 'Start Free Trial', ctaLink: '#trial' } },
      { id: 'features', type: 'features', label: 'Why Choose Us', enabled: true, content: { title: 'Everything You Need', items: ['250+ Equipment Pieces', 'Expert Personal Trainers', 'Group Classes Daily', '24/7 Access', 'Nutrition Guidance', 'Steam & Sauna'] } },
      { id: 'pricing', type: 'pricing', label: 'Membership Plans', enabled: true, content: { title: 'Choose Your Plan' } },
      { id: 'stats', type: 'stats', label: 'Our Numbers', enabled: true, content: { stats: ['500+ Active Members', '15 Expert Trainers', '50+ Classes/Week', '98% Satisfaction Rate'] } },
      { id: 'team', type: 'team', label: 'Our Trainers', enabled: true, content: { title: 'Expert Trainers' } },
      { id: 'testimonials', type: 'testimonials', label: 'Success Stories', enabled: true, content: { title: 'Member Transformations' } },
      { id: 'contact', type: 'contact', label: 'Join Now', enabled: true, content: { title: 'Start Your Journey', email: 'hello@yourgym.in' } },
    ],
  },
  {
    id: 'photography',
    label: 'Photography Studio',
    category: 'Creative',
    emoji: '📸',
    description: 'Photographers, videographers, and creative studios',
    suggestedThemes: ['midnight', 'slate', 'espresso'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero', enabled: true, content: { headline: 'Capturing Moments That Last Forever', subtext: 'Award-winning photography for weddings, portraits, events, and brands', cta: 'View Portfolio', ctaLink: '#portfolio' } },
      { id: 'features', type: 'features', label: 'Services', enabled: true, content: { title: 'What We Shoot', items: ['Wedding & Pre-Wedding', 'Portrait Sessions', 'Product Photography', 'Corporate Events', 'Real Estate', 'Social Media Content'] } },
      { id: 'gallery', type: 'gallery', label: 'Portfolio', enabled: true, content: { title: 'Our Work' } },
      { id: 'pricing', type: 'pricing', label: 'Packages', enabled: true, content: { title: 'Photography Packages' } },
      { id: 'testimonials', type: 'testimonials', label: 'Client Reviews', enabled: true, content: { title: 'Happy Clients' } },
      { id: 'contact', type: 'contact', label: 'Book a Session', enabled: true, content: { title: 'Let\'s Create Together', email: 'studio@photography.in' } },
    ],
  },
  {
    id: 'agency',
    label: 'Agency / Studio',
    category: 'Business',
    emoji: '🚀',
    description: 'Design agencies, marketing studios, and consulting firms',
    suggestedThemes: ['midnight', 'violet', 'slate'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero', enabled: true, content: { headline: 'We Build Brands That Win', subtext: 'Strategy, design, and digital marketing that drives real growth for ambitious businesses', cta: 'See Our Work', ctaLink: '#work' } },
      { id: 'features', type: 'features', label: 'Services', enabled: true, content: { title: 'What We Do', items: ['Brand Strategy', 'UI/UX Design', 'Web Development', 'SEO & Content', 'Social Media', 'Performance Marketing'] } },
      { id: 'stats', type: 'stats', label: 'Results', enabled: true, content: { stats: ['200+ Brands Built', '₹50Cr+ Revenue Generated', '98% Client Retention', 'Awards Won'] } },
      { id: 'gallery', type: 'gallery', label: 'Case Studies', enabled: true, content: { title: 'Our Work' } },
      { id: 'team', type: 'team', label: 'Our Team', enabled: true, content: { title: 'The People Behind the Magic' } },
      { id: 'pricing', type: 'pricing', label: 'Packages', enabled: true, content: { title: 'Engagement Models' } },
      { id: 'testimonials', type: 'testimonials', label: 'Testimonials', enabled: true, content: { title: 'Client Stories' } },
      { id: 'contact', type: 'contact', label: 'Start a Project', enabled: true, content: { title: 'Let\'s Build Something Great', email: 'hello@agency.in' } },
    ],
  },
  {
    id: 'clinic',
    label: 'Clinic',
    category: 'Healthcare',
    emoji: '🏥',
    description: 'Medical clinics, doctor chambers, dental practices',
    suggestedThemes: ['slate', 'forest', 'ocean'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Your Health, Our Priority', subtext: 'Compassionate care, modern diagnostics, and experienced doctors — all under one roof in the heart of your city', cta: 'Book Appointment', ctaLink: '#appointment' } },
      { id: 'about', type: 'about', label: 'About Us', enabled: true, content: { title: 'Caring for Families Since 2005', body: 'Sanjivani Clinic has been a trusted name in primary and preventive healthcare for over 18 years. Our team of qualified doctors and trained staff are committed to making quality medical care accessible and affordable for every family in the community.', image: '' } },
      { id: 'features', type: 'features', label: 'Our Services', enabled: true, content: { title: 'Comprehensive Healthcare Services', items: ['General Medicine & OPD', 'Paediatrics', 'Gynaecology & Obstetrics', 'Pathology & Blood Tests', 'ECG & Ultrasound', 'Vaccination Drive', 'Telemedicine Consultations', 'Health Check-up Packages'] } },
      { id: 'team', type: 'team', label: 'Our Doctors', enabled: true, content: { title: 'Meet Our Medical Team' } },
      { id: 'stats', type: 'stats', label: 'At a Glance', enabled: true, content: { stats: ['18+ Years of Practice', '40,000+ Patients Treated', '8 Specialist Doctors', 'Mon–Sat: 8 AM – 9 PM'] } },
      { id: 'testimonials', type: 'testimonials', label: 'Patient Testimonials', enabled: true, content: { title: 'What Our Patients Say' } },
      { id: 'hours', type: 'hours', label: 'Timings & Location', enabled: true, content: { weekdays: 'Mon–Sat: 8:00 AM – 9:00 PM', weekends: 'Sunday: 9:00 AM – 1:00 PM (Emergency Only)', address: '14 Nehru Nagar, Pune 411004', phone: '+91 20 2567 8900' } },
      { id: 'contact', type: 'contact', label: 'Book Appointment', enabled: true, content: { title: 'Schedule a Consultation', email: 'appointments@sanjivaniclinic.in' } },
    ],
  },
  {
    id: 'hospital',
    label: 'Hospital',
    category: 'Healthcare',
    emoji: '🏨',
    description: 'Multi-specialty hospitals and diagnostic centres',
    suggestedThemes: ['ocean', 'slate', 'forest'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Advanced Care. Human Touch.', subtext: 'A 200-bed multi-specialty hospital delivering world-class treatment with the warmth of a family doctor', cta: 'Find a Doctor', ctaLink: '#doctors' } },
      { id: 'features', type: 'features', label: 'Specialties', enabled: true, content: { title: 'Our Medical Specialties', items: ['Cardiology & Cardiac Surgery', 'Orthopaedics & Joint Replacement', 'Neurology & Neurosurgery', 'Oncology & Cancer Care', 'Nephrology & Dialysis', 'Emergency & Trauma', 'Maternity & NICU', 'Radiology & Imaging'] } },
      { id: 'stats', type: 'stats', label: 'Hospital at a Glance', enabled: true, content: { stats: ['200-Bed Capacity', '60+ Senior Consultants', 'NABH Accredited', '24×7 Emergency'] } },
      { id: 'team', type: 'team', label: 'Our Doctors', enabled: true, content: { title: 'Senior Consultants & Specialists' } },
      { id: 'gallery', type: 'gallery', label: 'Facilities', enabled: true, content: { title: 'State-of-the-Art Infrastructure' } },
      { id: 'testimonials', type: 'testimonials', label: 'Patient Stories', enabled: true, content: { title: 'Recoveries That Inspire' } },
      { id: 'hours', type: 'hours', label: 'Location & Emergency', enabled: true, content: { weekdays: 'OPD: Mon–Sat 8:00 AM – 7:00 PM', weekends: 'Emergency & ICU: 24×7', address: 'Plot 7, Sector 15, Navi Mumbai 400706', phone: '+91 22 6100 0000' } },
      { id: 'contact', type: 'contact', label: 'Contact Us', enabled: true, content: { title: 'Get in Touch', email: 'care@mediverthospital.in' } },
    ],
  },
  {
    id: 'dental',
    label: 'Dental Clinic',
    category: 'Healthcare',
    emoji: '🦷',
    description: 'Dental clinics and orthodontic practices',
    suggestedThemes: ['ocean', 'sage', 'slate'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Smile Brighter. Live Confidently.', subtext: 'Painless treatments, advanced technology, and a gentle touch — your perfect smile is just an appointment away', cta: 'Book Free Consultation', ctaLink: '#consultation' } },
      { id: 'about', type: 'about', label: 'About Us', enabled: true, content: { title: 'Precision Dentistry with a Gentle Touch', body: 'Dr. Priya Dental Care has been delivering pain-free, affordable dental treatment to patients across Hyderabad since 2012. We use ISO-certified sterilisation protocols and the latest digital X-ray equipment to ensure safe, accurate, and comfortable care for patients of all ages.', image: '' } },
      { id: 'features', type: 'features', label: 'Treatments', enabled: true, content: { title: 'Full Range of Dental Services', items: ['Teeth Cleaning & Scaling', 'Tooth Fillings & RCT', 'Dental Implants', 'Braces & Aligners', 'Smile Makeover', 'Kids Dentistry', 'Wisdom Tooth Extraction', 'Crowns & Bridges'] } },
      { id: 'pricing', type: 'pricing', label: 'Treatment Charges', enabled: true, content: { title: 'Transparent, Affordable Pricing' } },
      { id: 'team', type: 'team', label: 'Our Dentists', enabled: true, content: { title: 'Meet Your Smile Experts' } },
      { id: 'testimonials', type: 'testimonials', label: 'Patient Reviews', enabled: true, content: { title: 'Happy Smiles All Around' } },
      { id: 'hours', type: 'hours', label: 'Clinic Hours', enabled: true, content: { weekdays: 'Mon–Sat: 9:30 AM – 8:00 PM', weekends: 'Sunday: 10:00 AM – 2:00 PM', address: '22 Banjara Hills Road No.1, Hyderabad 500034', phone: '+91 40 4444 5555' } },
      { id: 'contact', type: 'contact', label: 'Book Appointment', enabled: true, content: { title: 'Schedule Your Visit', email: 'smile@priyadentalcare.in' } },
    ],
  },
  {
    id: 'pharmacy',
    label: 'Pharmacy',
    category: 'Healthcare',
    emoji: '💊',
    description: 'Pharmacies, medical stores, and health shops',
    suggestedThemes: ['forest', 'sage', 'ocean'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Your Trusted Medical Store', subtext: 'Genuine medicines, health products, and expert pharmacist advice — available 7 days a week', cta: 'Upload Prescription', ctaLink: '#prescription' } },
      { id: 'features', type: 'features', label: 'What We Stock', enabled: true, content: { title: 'Everything for Your Health Needs', items: ['Prescription Medicines', 'OTC & Generic Drugs', 'Baby & Mother Care', 'Vitamins & Supplements', 'Surgical Supplies', 'Ayurvedic & Homeopathy', 'Diabetic & BP Monitors', 'Home Delivery Available'] } },
      { id: 'stats', type: 'stats', label: 'Our Reach', enabled: true, content: { stats: ['5,000+ Products in Stock', 'FSSAI & Drug Licence Certified', '30-Minute Home Delivery', 'Open 365 Days'] } },
      { id: 'testimonials', type: 'testimonials', label: 'Customer Reviews', enabled: true, content: { title: 'Trusted by Thousands of Families' } },
      { id: 'faq', type: 'faq', label: 'FAQ', enabled: true, content: { title: 'Frequently Asked Questions' } },
      { id: 'hours', type: 'hours', label: 'Store Hours', enabled: true, content: { weekdays: 'Mon–Sat: 8:00 AM – 10:00 PM', weekends: 'Sunday: 9:00 AM – 8:00 PM', address: 'Shop 3, Shivaji Market, Nashik 422001', phone: '+91 253 660 7890' } },
      { id: 'contact', type: 'contact', label: 'Contact Us', enabled: true, content: { title: 'Order or Enquire', email: 'orders@lifecaremedicals.in' } },
    ],
  },
  {
    id: 'school',
    label: 'School',
    category: 'Education',
    emoji: '🏫',
    description: 'Schools, coaching centres, and tutorial institutes',
    suggestedThemes: ['golden', 'ocean', 'forest'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Nurturing Minds. Building Futures.', subtext: 'A CBSE-affiliated school offering holistic education, co-curricular excellence, and a safe learning environment for classes Nursery to XII', cta: 'Apply for Admission', ctaLink: '#admissions' } },
      { id: 'about', type: 'about', label: 'About Our School', enabled: true, content: { title: 'Shaping Tomorrow\'s Leaders Since 1998', body: 'Vidyashree Public School has been committed to academic excellence and value-based education for over 25 years. Our 5-acre campus, qualified faculty, and modern infrastructure provide every child the environment they need to discover their strengths and achieve their potential.', image: '' } },
      { id: 'features', type: 'features', label: 'Why Choose Us', enabled: true, content: { title: 'A School That Cares Beyond Academics', items: ['CBSE Affiliated (Up to Class XII)', 'Smart Classrooms & Digital Labs', 'Dedicated Sports & Activity Ground', 'NCC, NSS & Eco Club', 'Expert Counsellor on Campus', 'School Bus Facility (35 Routes)', 'Annual Scholarships for Toppers', 'Strong Alumni Network'] } },
      { id: 'stats', type: 'stats', label: 'Achievements', enabled: true, content: { stats: ['2,800+ Students Enrolled', '96% Board Pass Rate', '120+ Faculty Members', '25+ National Award Winners'] } },
      { id: 'gallery', type: 'gallery', label: 'Campus Life', enabled: true, content: { title: 'Life at Vidyashree' } },
      { id: 'testimonials', type: 'testimonials', label: 'Parent Testimonials', enabled: true, content: { title: 'What Parents and Alumni Say' } },
      { id: 'faq', type: 'faq', label: 'Admissions FAQ', enabled: true, content: { title: 'Admission Process & FAQs' } },
      { id: 'contact', type: 'contact', label: 'Enquire Now', enabled: true, content: { title: 'Admission Enquiry', email: 'admissions@vidyashreeschool.in' } },
    ],
  },
  {
    id: 'coaching',
    label: 'Coaching Centre',
    category: 'Education',
    emoji: '📖',
    description: 'IIT/NEET coaching, CA coaching, and skill training centres',
    suggestedThemes: ['midnight', 'slate', 'violet'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Crack IIT. Clear NEET. Change Your Life.', subtext: 'Structured batches, expert faculty, and a proven methodology trusted by 10,000+ students across India', cta: 'Enroll for Free Demo', ctaLink: '#demo' } },
      { id: 'features', type: 'features', label: 'Our Courses', enabled: true, content: { title: 'What We Teach', items: ['IIT-JEE Mains & Advanced', 'NEET UG & PG', 'Class XI–XII Foundation', 'Olympiad & KVPY', 'Crash Courses', 'Online Batches Available', 'Weekend & Evening Batches', 'Doubt-Clearing Sessions'] } },
      { id: 'stats', type: 'stats', label: 'Our Results', enabled: true, content: { stats: ['10,000+ Students Enrolled', '87% Selection Rate (2024)', '320 IIT Selections in 5 Years', '500+ NEET Qualifiers'] } },
      { id: 'team', type: 'team', label: 'Our Faculty', enabled: true, content: { title: 'IITian & Expert Faculty' } },
      { id: 'pricing', type: 'pricing', label: 'Fee Structure', enabled: true, content: { title: 'Batch Fees & Scholarships' } },
      { id: 'testimonials', type: 'testimonials', label: 'Student Success Stories', enabled: true, content: { title: 'Toppers Speak' } },
      { id: 'faq', type: 'faq', label: 'FAQ', enabled: true, content: { title: 'Common Questions Before You Enroll' } },
      { id: 'contact', type: 'contact', label: 'Enroll Now', enabled: true, content: { title: 'Book a Free Demo Class', email: 'admissions@apexcoaching.in' } },
    ],
  },
  {
    id: 'hotel',
    label: 'Hotel & Homestay',
    category: 'Hospitality',
    emoji: '🏨',
    description: 'Boutique hotels, homestays, and guesthouses',
    suggestedThemes: ['espresso', 'golden', 'terracotta'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Where Heritage Meets Comfort', subtext: 'A handcrafted boutique stay nestled in the hills of Coorg — wake up to mist, birdsong, and a cup of estate coffee', cta: 'Check Availability', ctaLink: '#booking' } },
      { id: 'about', type: 'about', label: 'Our Story', enabled: true, content: { title: 'A Home Away from Home', body: 'Nestled on a 15-acre coffee estate, The Misty Bungalow has been welcoming travellers since 2011. Each room is uniquely decorated with local art, handwoven textiles, and heritage furniture — a true reflection of Kodagu\'s rich culture and landscape.', image: '' } },
      { id: 'features', type: 'features', label: 'Amenities', enabled: true, content: { title: 'What We Offer', items: ['8 Individually Styled Rooms', 'Estate-to-Table Breakfast', 'Bonfire & Evening Tea', 'Trekking & Plantation Walk', 'Yoga Deck & Meditation Space', 'Airport Pickup from Mangaluru', 'Pet-Friendly Policy', 'Free Parking'] } },
      { id: 'pricing', type: 'pricing', label: 'Room Tariff', enabled: true, content: { title: 'Tariff & Packages' } },
      { id: 'gallery', type: 'gallery', label: 'Photo Gallery', enabled: true, content: { title: 'Experience the Misty Bungalow' } },
      { id: 'testimonials', type: 'testimonials', label: 'Guest Reviews', enabled: true, content: { title: 'What Our Guests Are Saying' } },
      { id: 'faq', type: 'faq', label: 'FAQ', enabled: true, content: { title: 'Before You Book' } },
      { id: 'contact', type: 'contact', label: 'Make a Booking', enabled: true, content: { title: 'Reserve Your Stay', email: 'stay@mistybungalow.in' } },
    ],
  },
  {
    id: 'realestate',
    label: 'Real Estate',
    category: 'Real Estate',
    emoji: '🏠',
    description: 'Property builders, brokers, and housing projects',
    suggestedThemes: ['slate', 'midnight', 'golden'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Find the Home You Deserve', subtext: 'Premium residential and commercial properties across Hyderabad, Pune, and Bengaluru — from ₹40 Lakhs onwards', cta: 'Explore Properties', ctaLink: '#properties' } },
      { id: 'features', type: 'features', label: 'Why Choose Us', enabled: true, content: { title: 'The Aryan Estates Advantage', items: ['RERA-Registered Projects', 'Ready-to-Move & Under-Construction', 'Transparent Pricing — No Hidden Charges', 'Home Loan Assistance from 10+ Banks', 'Post-Purchase Property Management', 'Resale & Rental Services', 'Site Visit Arranged Within 24 Hours', 'NRI Investment Desk'] } },
      { id: 'stats', type: 'stats', label: 'Track Record', enabled: true, content: { stats: ['1,200+ Families Housed', '₹800 Cr+ in Transactions', '18 Completed Projects', '4 Cities, 1 Vision'] } },
      { id: 'gallery', type: 'gallery', label: 'Project Gallery', enabled: true, content: { title: 'Our Completed & Ongoing Projects' } },
      { id: 'testimonials', type: 'testimonials', label: 'Client Stories', enabled: true, content: { title: 'Happy Homeowners Speak' } },
      { id: 'team', type: 'team', label: 'Our Team', enabled: true, content: { title: 'Meet Our Property Experts' } },
      { id: 'faq', type: 'faq', label: 'Property FAQ', enabled: true, content: { title: 'Buying a Home? Start Here.' } },
      { id: 'contact', type: 'contact', label: 'Schedule a Visit', enabled: true, content: { title: 'Book a Free Site Visit', email: 'sales@aryanestates.in' } },
    ],
  },
  {
    id: 'lawyer',
    label: 'Law Firm',
    category: 'Professional Services',
    emoji: '⚖️',
    description: 'Law firms and legal consultants',
    suggestedThemes: ['midnight', 'slate', 'espresso'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Trusted Legal Counsel. Fearless Advocacy.', subtext: 'Protecting your rights and interests across civil, criminal, corporate, and family law matters in courts across India', cta: 'Book a Consultation', ctaLink: '#consult' } },
      { id: 'about', type: 'about', label: 'About the Firm', enabled: true, content: { title: 'Over Two Decades of Legal Excellence', body: 'Mehta & Associates was founded in 2001 with a singular purpose: to deliver uncompromising legal representation to individuals, families, and businesses. Our team of 14 advocates practices before the Delhi High Court, Supreme Court, and district courts across North India.', image: '' } },
      { id: 'features', type: 'features', label: 'Practice Areas', enabled: true, content: { title: 'Areas of Practice', items: ['Civil & Commercial Litigation', 'Criminal Defence', 'Corporate & Company Law', 'Property & Real Estate', 'Family Law & Divorce', 'Labour & Employment', 'Intellectual Property', 'Consumer Forum Matters'] } },
      { id: 'team', type: 'team', label: 'Our Advocates', enabled: true, content: { title: 'The Legal Team' } },
      { id: 'stats', type: 'stats', label: 'Our Record', enabled: true, content: { stats: ['2,000+ Cases Handled', '85% Win/Settlement Rate', '23 Years of Practice', 'Delhi HC & Supreme Court'] } },
      { id: 'testimonials', type: 'testimonials', label: 'Client Testimonials', enabled: true, content: { title: 'What Our Clients Say' } },
      { id: 'faq', type: 'faq', label: 'Legal FAQ', enabled: true, content: { title: 'Common Legal Questions Answered' } },
      { id: 'contact', type: 'contact', label: 'Consult Us', enabled: true, content: { title: 'Schedule a Confidential Consultation', email: 'consult@mehtaassociates.in' } },
    ],
  },
  {
    id: 'ca_firm',
    label: 'CA / Accounting Firm',
    category: 'Professional Services',
    emoji: '📋',
    description: 'Chartered accountants and tax consultants',
    suggestedThemes: ['slate', 'ocean', 'midnight'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Smart Finance. Sound Compliance.', subtext: 'Expert CA services for GST, Income Tax, Audit, and Business Advisory — helping businesses stay compliant and grow', cta: 'Get a Free Consultation', ctaLink: '#consult' } },
      { id: 'features', type: 'features', label: 'Services', enabled: true, content: { title: 'Our Services', items: ['Income Tax Return Filing', 'GST Registration & Filing', 'Company Incorporation', 'Statutory & Tax Audit', 'ROC Compliance', 'Project Finance & CMA Reports', 'FEMA & RBI Compliances', 'Business Valuation'] } },
      { id: 'stats', type: 'stats', label: 'Our Track Record', enabled: true, content: { stats: ['500+ Active Clients', '₹200 Cr+ Tax Saved', '15 Years in Practice', 'ICAI Registered Firm'] } },
      { id: 'team', type: 'team', label: 'Our Partners', enabled: true, content: { title: 'Meet the Partners' } },
      { id: 'testimonials', type: 'testimonials', label: 'Client Testimonials', enabled: true, content: { title: 'Trusted by Businesses Across India' } },
      { id: 'pricing', type: 'pricing', label: 'Fee Packages', enabled: true, content: { title: 'Transparent Retainer & Filing Fees' } },
      { id: 'faq', type: 'faq', label: 'Tax FAQ', enabled: true, content: { title: 'Common Questions on GST, ITR & More' } },
      { id: 'contact', type: 'contact', label: 'Get in Touch', enabled: true, content: { title: 'Talk to a CA Today', email: 'info@guptaandco.in' } },
    ],
  },
  {
    id: 'ecommerce',
    label: 'E-Commerce Store',
    category: 'Retail',
    emoji: '🛒',
    description: 'Online stores and product-based businesses',
    suggestedThemes: ['midnight', 'violet', 'ocean'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Shop Smart. Save More.', subtext: 'Thousands of products, genuine brands, and pan-India delivery in 2–5 days. Now offering EMI on orders above ₹3,000', cta: 'Shop Now', ctaLink: '#products' } },
      { id: 'features', type: 'features', label: 'Why Shop With Us', enabled: true, content: { title: 'The KartMela Promise', items: ['100% Genuine Products', 'Free Shipping on Orders ₹499+', 'Easy 7-Day Returns', 'Secure UPI / Card / COD', 'Same-Day Dispatch Before 2 PM', 'WhatsApp Order Tracking', 'Exclusive Member Deals', 'GST Invoice on Every Order'] } },
      { id: 'menu', type: 'menu', label: 'Shop by Category', enabled: true, content: { title: 'Browse Categories', categories: ['Electronics', 'Fashion', 'Home & Kitchen', 'Beauty', 'Sports & Fitness', 'Books & Stationery'] } },
      { id: 'stats', type: 'stats', label: 'Numbers', enabled: true, content: { stats: ['50,000+ Happy Customers', '10,000+ Products', '4.7★ Average Rating', 'Ships to 500+ Pincodes'] } },
      { id: 'testimonials', type: 'testimonials', label: 'Customer Reviews', enabled: true, content: { title: 'What Shoppers Are Saying' } },
      { id: 'faq', type: 'faq', label: 'FAQ', enabled: true, content: { title: 'Shipping, Returns & Payments' } },
      { id: 'contact', type: 'contact', label: 'Support', enabled: true, content: { title: 'Customer Support', email: 'support@kartmela.in' } },
    ],
  },
  {
    id: 'fashion',
    label: 'Fashion Boutique',
    category: 'Retail',
    emoji: '👗',
    description: 'Fashion boutiques, clothing brands, and accessories',
    suggestedThemes: ['rose', 'midnight', 'violet'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Dress the Story You Want to Tell', subtext: 'Contemporary Indian fashion blending traditional craft with modern silhouettes — ethically made, thoughtfully priced', cta: 'Shop New Arrivals', ctaLink: '#collection' } },
      { id: 'about', type: 'about', label: 'Our Story', enabled: true, content: { title: 'Born in Jaipur. Loved Across India.', body: 'Rangsutra Collective was started in 2016 by two sisters who believed Indian women deserved fashion that honoured its artisan roots. Every piece in our collection is made in collaboration with weavers and block-printers from Rajasthan and Gujarat.', image: '' } },
      { id: 'menu', type: 'menu', label: 'Collections', enabled: true, content: { title: 'Shop by Category', categories: ['Kurtas & Sets', 'Sarees & Dupattas', 'Western Wear', 'Bridal Edit', 'Men\'s Wear', 'Accessories'] } },
      { id: 'features', type: 'features', label: 'Why Rangsutra', enabled: true, content: { title: 'Fashion with a Conscience', items: ['Handloom & Handblock Fabrics', 'Artisan-Made in India', 'Sizes XS to 4XL', 'Custom Tailoring Available', 'Free Shipping Above ₹1,200', 'Easy Exchange & Returns'] } },
      { id: 'gallery', type: 'gallery', label: 'Lookbook', enabled: true, content: { title: 'Season Lookbook' } },
      { id: 'testimonials', type: 'testimonials', label: 'Customer Love', enabled: true, content: { title: 'From Our Community' } },
      { id: 'contact', type: 'contact', label: 'Contact', enabled: true, content: { title: 'Style Consultation & Orders', email: 'hello@rangsutra.in' } },
    ],
  },
  {
    id: 'wedding',
    label: 'Wedding Planner',
    category: 'Events',
    emoji: '💍',
    description: 'Wedding planners and event management companies',
    suggestedThemes: ['rose', 'golden', 'espresso'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Your Dream Wedding, Flawlessly Executed.', subtext: 'From intimate gatherings to grand celebrations — we create weddings that reflect your love story, down to the last detail', cta: 'Start Planning', ctaLink: '#enquiry' } },
      { id: 'about', type: 'about', label: 'About Us', enabled: true, content: { title: 'Creating Celebrations That Last a Lifetime', body: 'With over 200 weddings planned across venues in Rajasthan, Goa, Kerala, and the Himalayas, Shaadi Stories is one of India\'s most trusted wedding planning companies. Our dedicated team of planners, decorators, and coordinators ensures your special day is stress-free, seamless, and simply magical.', image: '' } },
      { id: 'features', type: 'features', label: 'Services', enabled: true, content: { title: 'Complete Wedding Planning Services', items: ['Venue Sourcing & Booking', 'Theme Design & Décor', 'Mehendi, Sangeet & Haldi Events', 'Catering & Menu Curation', 'Photography & Videography', 'Entertainment & DJs', 'Guest Management & Stays', 'Honeymoon Planning'] } },
      { id: 'pricing', type: 'pricing', label: 'Packages', enabled: true, content: { title: 'Wedding Packages Starting ₹3.5 Lakhs' } },
      { id: 'gallery', type: 'gallery', label: 'Wedding Gallery', enabled: true, content: { title: 'Real Weddings We\'ve Planned' } },
      { id: 'stats', type: 'stats', label: 'Our Journey', enabled: true, content: { stats: ['200+ Weddings Planned', 'Across 12 States', '4.9★ on WeddingWire', '8 Destination Wedding Experts'] } },
      { id: 'testimonials', type: 'testimonials', label: 'Couple Testimonials', enabled: true, content: { title: 'Words from Our Couples' } },
      { id: 'contact', type: 'contact', label: 'Plan Your Wedding', enabled: true, content: { title: 'Let\'s Plan Together', email: 'hello@shaadistories.in' } },
    ],
  },
  {
    id: 'caterer',
    label: 'Catering Service',
    category: 'Food & Beverage',
    emoji: '🍲',
    description: 'Catering services and cloud kitchens',
    suggestedThemes: ['terracotta', 'golden', 'espresso'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Feast Worthy Food for Every Occasion', subtext: 'Corporate lunches, wedding feasts, birthday spreads, and daily tiffin services — made fresh, delivered on time, every time', cta: 'Request a Quote', ctaLink: '#quote' } },
      { id: 'features', type: 'features', label: 'What We Cater', enabled: true, content: { title: 'Our Catering Services', items: ['Wedding & Reception Buffets', 'Corporate Lunch Packages', 'Birthday & Anniversary Parties', 'Pooja & Religious Functions', 'Daily Tiffin Subscription', 'Live Counter Setups', 'North & South Indian Cuisine', 'Custom Menu Planning'] } },
      { id: 'menu', type: 'menu', label: 'Menu', enabled: true, content: { title: 'Sample Menus', categories: ['Veg Thali', 'Non-Veg Thali', 'Wedding Package', 'Corporate Lunch', 'Continental'] } },
      { id: 'stats', type: 'stats', label: 'Our Scale', enabled: true, content: { stats: ['500+ Events Catered', 'Up to 5,000 Plates/Day', 'FSSAI Certified Kitchen', '12 Years in Business'] } },
      { id: 'gallery', type: 'gallery', label: 'Food Gallery', enabled: true, content: { title: 'A Feast for the Eyes' } },
      { id: 'testimonials', type: 'testimonials', label: 'Client Reviews', enabled: true, content: { title: 'Praise from Our Patrons' } },
      { id: 'contact', type: 'contact', label: 'Get a Quote', enabled: true, content: { title: 'Tell Us About Your Event', email: 'bookings@rasoicaterers.in' } },
    ],
  },
  {
    id: 'travel',
    label: 'Travel Agency',
    category: 'Travel',
    emoji: '✈️',
    description: 'Travel agencies and tour operators',
    suggestedThemes: ['ocean', 'forest', 'sage'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Your Next Adventure Awaits', subtext: 'Carefully crafted holiday packages for Himachal, Rajasthan, Kerala, Goa, Europe, and beyond — tailored to your dream itinerary', cta: 'Explore Packages', ctaLink: '#packages' } },
      { id: 'features', type: 'features', label: 'What We Offer', enabled: true, content: { title: 'End-to-End Travel Services', items: ['Customised Holiday Packages', 'Group & Family Tours', 'Honeymoon Specials', 'Corporate Travel Management', 'Visa Assistance', 'Hotel & Flight Booking', 'Airport Transfers', 'Travel Insurance'] } },
      { id: 'menu', type: 'menu', label: 'Destinations', enabled: true, content: { title: 'Popular Destinations', categories: ['Himachal & Uttarakhand', 'Rajasthan', 'Kerala & Goa', 'Northeast India', 'International', 'Pilgrim Tours'] } },
      { id: 'stats', type: 'stats', label: 'Our Track Record', enabled: true, content: { stats: ['15,000+ Happy Travellers', '200+ Destinations Covered', 'IATA Certified Agency', '12 Years in the Business'] } },
      { id: 'gallery', type: 'gallery', label: 'Travel Gallery', enabled: true, content: { title: 'Journeys We\'ve Made Possible' } },
      { id: 'testimonials', type: 'testimonials', label: 'Traveller Reviews', enabled: true, content: { title: 'Stories from Our Travellers' } },
      { id: 'contact', type: 'contact', label: 'Plan Your Trip', enabled: true, content: { title: 'Tell Us Where You Want to Go', email: 'bookings@ghoomoindia.in' } },
    ],
  },
  {
    id: 'ngo',
    label: 'NGO / Non-Profit',
    category: 'Social',
    emoji: '🤝',
    description: 'NGOs, trusts, and non-profit organizations',
    suggestedThemes: ['sage', 'forest', 'ocean'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Together, We Can Change Lives.', subtext: 'Working at the intersection of education, nutrition, and livelihood to uplift underprivileged communities across rural India', cta: 'Donate Now', ctaLink: '#donate' } },
      { id: 'about', type: 'about', label: 'Our Mission', enabled: true, content: { title: 'Rooted in Communities. Driven by Purpose.', body: 'Pragati Foundation is a registered NGO working since 2008 across 200 villages in Vidarbha and Bundelkhand. We believe lasting change happens when communities are empowered from within — through education for girls, vocational training for youth, and support for smallholder farmers.', image: '' } },
      { id: 'features', type: 'features', label: 'Our Programmes', enabled: true, content: { title: 'What We Work On', items: ['Girls\' Education Scholarships', 'Digital Literacy for Rural Youth', 'Midday Meal Programme', 'Women\'s Self-Help Groups', 'Watershed & Soil Conservation', 'Healthcare Camps in Villages', 'Skill Training & Placement', 'Child Rights & Protection'] } },
      { id: 'stats', type: 'stats', label: 'Our Impact', enabled: true, content: { stats: ['50,000+ Beneficiaries', '200 Villages Reached', '80Cr+ in CSR Grants Managed', '12:80 Year Track Record'] } },
      { id: 'gallery', type: 'gallery', label: 'Field Gallery', enabled: true, content: { title: 'Impact Through Our Lens' } },
      { id: 'blog', type: 'blog', label: 'Stories of Change', enabled: true, content: { title: 'Impact Stories from the Ground' } },
      { id: 'testimonials', type: 'testimonials', label: 'Voices from the Field', enabled: true, content: { title: 'Beneficiaries Share Their Stories' } },
      { id: 'contact', type: 'contact', label: 'Get Involved', enabled: true, content: { title: 'Partner, Volunteer, or Donate', email: 'connect@pragatifoundation.org' } },
    ],
  },
  {
    id: 'autoservice',
    label: 'Auto Service Centre',
    category: 'Automotive',
    emoji: '🔧',
    description: 'Car service centres, garages, and auto dealers',
    suggestedThemes: ['midnight', 'slate', 'terracotta'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Your Car Deserves the Best Care', subtext: 'Authorised multi-brand car service centre offering periodic maintenance, repairs, detailing, and 24-hour breakdown assistance', cta: 'Book a Service', ctaLink: '#booking' } },
      { id: 'features', type: 'features', label: 'Services', enabled: true, content: { title: 'What We Service', items: ['Periodic Maintenance & Oil Change', 'Engine Diagnostics & Repair', 'Denting, Painting & Body Work', 'AC Service & Re-gas', 'Tyre & Wheel Alignment', 'Car Detailing & Ceramic Coating', 'Insurance Claim Assistance', 'Free Pick-up & Drop Within 10 km'] } },
      { id: 'stats', type: 'stats', label: 'Our Numbers', enabled: true, content: { stats: ['10,000+ Cars Serviced', 'ISO 9001 Certified Workshop', 'Multi-Brand Expertise', '24-Hour Breakdown Helpline'] } },
      { id: 'pricing', type: 'pricing', label: 'Service Packages', enabled: true, content: { title: 'Transparent Service Packages' } },
      { id: 'gallery', type: 'gallery', label: 'Workshop Gallery', enabled: true, content: { title: 'Our Workshop & Work' } },
      { id: 'testimonials', type: 'testimonials', label: 'Customer Reviews', enabled: true, content: { title: 'What Car Owners Say' } },
      { id: 'hours', type: 'hours', label: 'Workshop Hours', enabled: true, content: { weekdays: 'Mon–Sat: 8:00 AM – 7:00 PM', weekends: 'Sunday: 9:00 AM – 2:00 PM', address: 'Plot 55, MIDC Road, Aurangabad 431001', phone: '+91 240 660 4422' } },
      { id: 'contact', type: 'contact', label: 'Book a Service', enabled: true, content: { title: 'Schedule Your Car\'s Service', email: 'service@drivewellgarage.in' } },
    ],
  },
  {
    id: 'bakery',
    label: 'Bakery & Patisserie',
    category: 'Food & Beverage',
    emoji: '🥐',
    description: 'Artisan bakeries, patisseries, and home bakers',
    suggestedThemes: ['golden', 'terracotta', 'espresso'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Baked Fresh Every Morning, Just for You', subtext: 'Artisan breads, flaky croissants, and handmade cakes crafted with love in the heart of Pune — order by 8 PM for next-day pickup', cta: 'Order Now', ctaLink: '#order' } },
      { id: 'about', type: 'about', label: 'Our Story', enabled: true, content: { title: 'From Our Oven to Your Table', body: 'Mitti & Maida Bakery was born in a small home kitchen in Kothrud, Pune in 2019. What started as Sunday sourdough for neighbours has grown into a beloved artisan bakery trusted by over 2,000 happy customers. Every loaf, every tart, and every cake is made from scratch using unbleached flours, European-style butter, and no artificial preservatives.', image: '' } },
      { id: 'menu', type: 'menu', label: 'Our Bakes', enabled: true, content: { title: 'What\'s in the Oven', categories: ['Breads & Loaves', 'Croissants & Pastries', 'Cakes & Tarts', 'Cookies & Biscuits', 'Seasonal Specials', 'Custom Orders'] } },
      { id: 'features', type: 'features', label: 'Why We\'re Different', enabled: true, content: { title: 'Baked with Integrity', items: ['No Maida — Whole Wheat & Rye Options', 'Zero Artificial Preservatives', 'Custom Cakes for Every Occasion', 'Eggless Options Available', 'Same-Day Orders by Appointment', 'Free Delivery in 5 km Radius (Min ₹499)'] } },
      { id: 'gallery', type: 'gallery', label: 'Bake Gallery', enabled: true, content: { title: 'Fresh from the Oven' } },
      { id: 'testimonials', type: 'testimonials', label: 'Customer Reviews', enabled: true, content: { title: 'What Our Regulars Say' } },
      { id: 'hours', type: 'hours', label: 'Bakery Hours', enabled: true, content: { weekdays: 'Tue–Sun: 7:30 AM – 7:00 PM', weekends: 'Monday: Closed (Baking Day)', address: 'Shop 4, Panchvati Colony, Kothrud, Pune 411038', phone: '+91 98220 34567' } },
      { id: 'contact', type: 'contact', label: 'Place an Order', enabled: true, content: { title: 'Custom Orders & Enquiries', email: 'orders@mittiandmaida.in' } },
    ],
  },
  {
    id: 'juice_bar',
    label: 'Juice & Health Bar',
    category: 'Food & Beverage',
    emoji: '🥤',
    description: 'Juice bars, smoothie shops, and healthy food cafes',
    suggestedThemes: ['forest', 'sage', 'emerald_deep'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Drink Your Way to a Healthier You', subtext: 'Cold-pressed juices, superfood smoothies, and immunity boosters — made fresh to order with no added sugar or preservatives', cta: 'View Menu', ctaLink: '#menu' } },
      { id: 'about', type: 'about', label: 'Our Philosophy', enabled: true, content: { title: 'Real Fruit. Real Health. Real Fast.', body: 'GreenPulse was founded by nutritionist Kavya Menon in Koramangala, Bengaluru in 2021. Frustrated by sugary packaged juices, she built a bar that uses only fresh, locally sourced produce — no concentrates, no refined sugar, no shortcuts. Every glass is made in under 3 minutes and backed by a registered dietitian\'s recipes.', image: '' } },
      { id: 'menu', type: 'menu', label: 'Menu', enabled: true, content: { title: 'Our Menu', categories: ['Cold-Pressed Juices', 'Smoothie Bowls', 'Protein Shakes', 'Immunity Shots', 'Detox Plans', 'Healthy Snacks'] } },
      { id: 'features', type: 'features', label: 'Why GreenPulse', enabled: true, content: { title: 'The GreenPulse Promise', items: ['100% Fresh Produce — No Concentrates', 'No Added Sugar or Preservatives', 'Dietitian-Approved Recipes', 'Vegan & Diabetic-Friendly Options', 'Daily Detox Plans Available', 'Subscription Delivery in Bengaluru'] } },
      { id: 'stats', type: 'stats', label: 'Our Numbers', enabled: true, content: { stats: ['300+ Glasses Sold Daily', '40+ Items on Menu', 'Dietitian-Approved Recipes', '4.8★ on Swiggy'] } },
      { id: 'testimonials', type: 'testimonials', label: 'Customer Reviews', enabled: true, content: { title: 'Health Wins from Our Community' } },
      { id: 'hours', type: 'hours', label: 'We\'re Open', enabled: true, content: { weekdays: 'Mon–Sat: 7:00 AM – 9:00 PM', weekends: 'Sunday: 8:00 AM – 8:00 PM', address: '12 Koramangala 5th Block, Bengaluru 560095', phone: '+91 96860 12345' } },
      { id: 'contact', type: 'contact', label: 'Contact Us', enabled: true, content: { title: 'Bulk Orders & Subscriptions', email: 'hello@greenpulsebar.in' } },
    ],
  },
  {
    id: 'pharmacy_retail',
    label: 'Medical Store',
    category: 'Healthcare',
    emoji: '⚕️',
    description: 'Pharmacies, medical equipment stores',
    suggestedThemes: ['ocean', 'navy', 'teal_fresh'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Medicines & Health Products, Delivered to Your Door', subtext: 'Licensed pharmacy serving Jaipur since 2003 — genuine medicines, competitive pricing, and 30-minute home delivery on orders above ₹299', cta: 'Order Medicines', ctaLink: '#order' } },
      { id: 'about', type: 'about', label: 'About Us', enabled: true, content: { title: 'Your Neighbourhood Health Partner', body: 'Arogya Medical Store has been a trusted name in Vaishali Nagar, Jaipur for over 20 years. Licensed pharmacists on duty ensure every prescription is dispensed accurately and safely. We stock 8,000+ medicines from leading manufacturers and offer same-day home delivery across the city.', image: '' } },
      { id: 'features', type: 'features', label: 'What We Offer', enabled: true, content: { title: 'Complete Health Solutions', items: ['Prescription & OTC Medicines', 'Ayurvedic & Homeopathic Products', 'Diabetic Care & BP Monitors', 'Orthopaedic & Surgical Supplies', 'Baby & Maternal Care Products', 'Vitamins, Supplements & Nutraceuticals', 'Home Delivery in 30 Minutes', 'Licensed Pharmacist on Duty 24×7'] } },
      { id: 'stats', type: 'stats', label: 'Store Highlights', enabled: true, content: { stats: ['8,000+ Medicines in Stock', 'Drug Licence Certified', '20+ Years of Service', '30-Min Delivery in Jaipur'] } },
      { id: 'testimonials', type: 'testimonials', label: 'Customer Reviews', enabled: true, content: { title: 'Trusted by Thousands of Families' } },
      { id: 'faq', type: 'faq', label: 'FAQ', enabled: true, content: { title: 'Common Questions About Orders & Delivery' } },
      { id: 'hours', type: 'hours', label: 'Store Hours', enabled: true, content: { weekdays: 'Mon–Sat: 8:00 AM – 10:30 PM', weekends: 'Sunday: 9:00 AM – 9:00 PM', address: 'D-14, Vaishali Nagar, Jaipur 302021', phone: '+91 141 230 4567' } },
      { id: 'contact', type: 'contact', label: 'Order Now', enabled: true, content: { title: 'Upload Prescription or Enquire', email: 'orders@arogyamedicals.in' } },
    ],
  },
  {
    id: 'yoga',
    label: 'Yoga & Meditation',
    category: 'Health & Wellness',
    emoji: '🧘',
    description: 'Yoga studios, meditation centres, and wellness retreats',
    suggestedThemes: ['sage', 'forest', 'golden'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Find Your Stillness. Reclaim Your Strength.', subtext: 'Classical Hatha, Ashtanga, and Yin Yoga classes for all levels — in-studio and online, guided by certified instructors in Rishikesh tradition', cta: 'Book a Free Class', ctaLink: '#book' } },
      { id: 'about', type: 'about', label: 'Our Philosophy', enabled: true, content: { title: 'Yoga as a Way of Life', body: 'Ananda Yoga Shala was established in 2015 in Indiranagar, Bengaluru by Preethi Nair, a 500-hour RYT certified instructor trained under the Sivananda tradition in Rishikesh. Our studio is a quiet, judgement-free sanctuary for beginners and experienced practitioners alike — no competitive energy, just breathwork, movement, and mindfulness.', image: '' } },
      { id: 'features', type: 'features', label: 'Our Classes', enabled: true, content: { title: 'Classes for Every Body', items: ['Hatha Yoga (Beginner-Friendly)', 'Ashtanga & Vinyasa Flow', 'Yin Yoga & Restorative', 'Pranayama & Breathwork', 'Guided Meditation Sessions', 'Kids & Teen Yoga', 'Corporate Wellness Sessions', 'Weekend Retreat Programmes'] } },
      { id: 'pricing', type: 'pricing', label: 'Membership Plans', enabled: true, content: { title: 'Plans Starting from ₹1,200/Month' } },
      { id: 'team', type: 'team', label: 'Our Teachers', enabled: true, content: { title: 'Meet Your Instructors' } },
      { id: 'stats', type: 'stats', label: 'Our Community', enabled: true, content: { stats: ['800+ Active Students', '10 Certified Instructors', '60+ Classes Per Week', '9 Years of Practice'] } },
      { id: 'testimonials', type: 'testimonials', label: 'Student Stories', enabled: true, content: { title: 'How Yoga Changed Their Lives' } },
      { id: 'contact', type: 'contact', label: 'Join Us', enabled: true, content: { title: 'Book Your First Class Free', email: 'namaste@anandayogashala.in' } },
    ],
  },
  {
    id: 'tutor',
    label: 'Private Tutor',
    category: 'Education',
    emoji: '📝',
    description: 'Individual tutors and small home tuition centres',
    suggestedThemes: ['ocean', 'golden', 'navy'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'One-on-One Tuition That Gets Results', subtext: 'Personalised home and online tuition for Classes 6–12 in Maths, Science, and English — IIT-educated tutors, proven track record', cta: 'Book a Free Demo', ctaLink: '#demo' } },
      { id: 'about', type: 'about', label: 'About Me', enabled: true, content: { title: 'Hello, I\'m Arjun Sharma', body: 'I\'m a B.Tech graduate from IIT Roorkee with 8 years of tutoring experience in Delhi NCR. I specialise in helping Class 9–12 students build strong conceptual foundations in Physics, Chemistry, and Mathematics. My students have consistently scored above 90% in CBSE boards and cleared competitive exams including JEE Mains.', image: '' } },
      { id: 'features', type: 'features', label: 'What I Teach', enabled: true, content: { title: 'Subjects & Programmes', items: ['Mathematics (Class 6–12)', 'Physics & Chemistry (Class 9–12)', 'JEE Mains Preparation', 'CBSE Board Exam Focus', 'Doubt-Clearing Sessions', 'Home Tuition in South Delhi', 'Online Classes via Zoom', 'Study Material Provided'] } },
      { id: 'stats', type: 'stats', label: 'My Track Record', enabled: true, content: { stats: ['200+ Students Taught', '92% Students Score 90%+ in Boards', '8 Years of Experience', 'IIT Roorkee Alumni'] } },
      { id: 'pricing', type: 'pricing', label: 'Fee Structure', enabled: true, content: { title: 'Tuition Fees' } },
      { id: 'testimonials', type: 'testimonials', label: 'Parent & Student Reviews', enabled: true, content: { title: 'What Families Say' } },
      { id: 'faq', type: 'faq', label: 'FAQ', enabled: true, content: { title: 'Before You Enroll' } },
      { id: 'contact', type: 'contact', label: 'Book a Demo', enabled: true, content: { title: 'Schedule a Free Demo Class', email: 'arjun.tutors@gmail.com' } },
    ],
  },
  {
    id: 'interior',
    label: 'Interior Design',
    category: 'Creative',
    emoji: '🛋️',
    description: 'Interior designers, decorators, and home styling studios',
    suggestedThemes: ['espresso', 'charcoal', 'golden'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Spaces That Tell Your Story', subtext: 'Award-winning interior design studio crafting beautiful, functional homes and offices across Mumbai, Pune, and Goa — turnkey projects from ₹8 Lakhs', cta: 'View Portfolio', ctaLink: '#portfolio' } },
      { id: 'about', type: 'about', label: 'About the Studio', enabled: true, content: { title: 'Design-Led. Detail-Obsessed.', body: 'Arqa Studio was founded in 2017 by principal designer Meera Iyer, a graduate of the Sir J.J. School of Art. We believe every home has a soul — our job is to bring it to life. From material selection to final styling, we manage the entire project with one point of contact and a transparent budget process.', image: '' } },
      { id: 'features', type: 'features', label: 'Our Services', enabled: true, content: { title: 'What We Design', items: ['Residential Full-Home Interiors', 'Modular Kitchen & Wardrobes', 'Office & Commercial Design', 'Renovation & Refurbishment', '3D Walkthrough Before Execution', 'Material & Vendor Sourcing', 'Vastu-Compliant Layouts', 'Turnkey Project Management'] } },
      { id: 'gallery', type: 'gallery', label: 'Portfolio', enabled: true, content: { title: 'Our Design Portfolio' } },
      { id: 'stats', type: 'stats', label: 'Studio Numbers', enabled: true, content: { stats: ['150+ Projects Completed', '3 Cities — Mumbai, Pune, Goa', 'Featured in Architectural Digest India', '98% On-Time Delivery'] } },
      { id: 'pricing', type: 'pricing', label: 'Project Packages', enabled: true, content: { title: 'Design Packages & Investment' } },
      { id: 'testimonials', type: 'testimonials', label: 'Client Testimonials', enabled: true, content: { title: 'What Homeowners Say' } },
      { id: 'contact', type: 'contact', label: 'Start Your Project', enabled: true, content: { title: 'Let\'s Design Your Space', email: 'hello@arqastudio.in' } },
    ],
  },
  {
    id: 'architect',
    label: 'Architecture Firm',
    category: 'Professional Services',
    emoji: '🏗️',
    description: 'Architecture firms, structural consultants, urban planners',
    suggestedThemes: ['midnight', 'charcoal', 'slate'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Architecture That Endures.', subtext: 'From concept to completion — residential, commercial, and institutional architecture rooted in sustainability, context, and craft', cta: 'Explore Our Work', ctaLink: '#work' } },
      { id: 'about', type: 'about', label: 'About the Firm', enabled: true, content: { title: 'Building with Purpose Since 2008', body: 'Vaastu Architects is a Bengaluru-based practice founded by Ar. Rohan Desai and Ar. Supriya Kulkarni, both alumni of CEPT University, Ahmedabad. Our practice believes architecture must respond to climate, culture, and community — not just aesthetics. We work on residential bungalows, housing layouts, commercial complexes, and public infrastructure across South India.', image: '' } },
      { id: 'features', type: 'features', label: 'Services', enabled: true, content: { title: 'Architecture & Consulting Services', items: ['Residential Architecture & Bungalows', 'Apartment & Housing Layout Design', 'Commercial & Retail Projects', 'Institutional & Hospitality', 'Structural Consulting', 'Vastu-Integrated Design', 'BIM & 3D Modelling', 'LEED & Green Building Certification'] } },
      { id: 'gallery', type: 'gallery', label: 'Project Portfolio', enabled: true, content: { title: 'Selected Works' } },
      { id: 'stats', type: 'stats', label: 'Practice Overview', enabled: true, content: { stats: ['80+ Projects Completed', 'Council of Architecture Registered', '2 National Design Awards', '15 Years of Practice'] } },
      { id: 'team', type: 'team', label: 'Our Architects', enabled: true, content: { title: 'The Design Team' } },
      { id: 'testimonials', type: 'testimonials', label: 'Client Testimonials', enabled: true, content: { title: 'From Our Clients' } },
      { id: 'contact', type: 'contact', label: 'Discuss Your Project', enabled: true, content: { title: 'Start a Conversation', email: 'studio@vaastuarchitects.in' } },
    ],
  },
  {
    id: 'event_venue',
    label: 'Event Venue',
    category: 'Events',
    emoji: '🏛️',
    description: 'Banquet halls, wedding venues, and event spaces',
    suggestedThemes: ['rose', 'golden', 'burgundy'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'The Perfect Backdrop for Your Most Precious Moments', subtext: 'A grand 1,200-capacity banquet hall in the heart of Coimbatore — for weddings, receptions, conferences, and milestone celebrations', cta: 'Check Availability', ctaLink: '#enquiry' } },
      { id: 'about', type: 'about', label: 'About the Venue', enabled: true, content: { title: 'Where Memories Are Made', body: 'Sri Mahalakshmi Convention Centre has been Coimbatore\'s most sought-after event venue since 1998. Spanning 25,000 sq ft across three halls, the venue combines South Indian grandeur with modern conveniences — climate-controlled halls, state-of-the-art AV systems, in-house catering, and a dedicated events management team to ensure every celebration is flawless.', image: '' } },
      { id: 'features', type: 'features', label: 'Venue Highlights', enabled: true, content: { title: 'Everything for a Perfect Event', items: ['3 Halls: 150 to 1,200 Capacity', 'Central AC & Stage with LED Backdrop', 'In-House Catering — Veg & Non-Veg', 'Bridal Suite & Dressing Rooms', 'Dedicated Parking for 400+ Vehicles', 'Sound System & Projector Included', 'Floral Decoration Packages Available', 'Coordination Team on Site'] } },
      { id: 'pricing', type: 'pricing', label: 'Hall Packages', enabled: true, content: { title: 'Hall Hire & Event Packages' } },
      { id: 'gallery', type: 'gallery', label: 'Event Gallery', enabled: true, content: { title: 'Celebrations at Sri Mahalakshmi' } },
      { id: 'stats', type: 'stats', label: 'The Numbers', enabled: true, content: { stats: ['2,000+ Events Hosted', '25 Years in Business', '1,200 Max Capacity', '4.9★ on Google'] } },
      { id: 'testimonials', type: 'testimonials', label: 'Client Reviews', enabled: true, content: { title: 'What Families Are Saying' } },
      { id: 'contact', type: 'contact', label: 'Book the Venue', enabled: true, content: { title: 'Check Availability & Get a Quote', email: 'bookings@srimhlvenue.in' } },
    ],
  },
  {
    id: 'florist',
    label: 'Florist & Gift Shop',
    category: 'Retail',
    emoji: '🌸',
    description: 'Flower shops, gift stores, and event decoration',
    suggestedThemes: ['rose', 'sage', 'coral'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Say It with Flowers', subtext: 'Fresh blooms, handcrafted arrangements, and curated gifts for every occasion — delivered same day across Chennai', cta: 'Order Flowers', ctaLink: '#order' } },
      { id: 'about', type: 'about', label: 'Our Story', enabled: true, content: { title: 'Blooming Since 2010', body: 'Petal & Bloom is Chennai\'s favourite florist, started by Anu Krishnamurthy in a small shop in Nungambakkam. We source fresh flowers daily from Hosur and Bengaluru farms, ensuring every bouquet is vibrant and long-lasting. From single-stem roses to 500-arrangement wedding mandaps, we do it all with the same attention to detail.', image: '' } },
      { id: 'menu', type: 'menu', label: 'Shop by Occasion', enabled: true, content: { title: 'Browse Our Collections', categories: ['Birthday Bouquets', 'Wedding Flowers', 'Corporate Gifting', 'Anniversary Arrangements', 'Sympathy & Condolence', 'Festive Décor'] } },
      { id: 'features', type: 'features', label: 'Our Services', enabled: true, content: { title: 'What We Do', items: ['Fresh Flower Bouquets & Arrangements', 'Wedding & Event Flower Decoration', 'Corporate Gifting Programmes', 'Same-Day Delivery Across Chennai', 'Custom Flower Boxes & Hampers', 'Subscription Blooms for Offices & Homes'] } },
      { id: 'gallery', type: 'gallery', label: 'Floral Gallery', enabled: true, content: { title: 'Our Arrangements' } },
      { id: 'testimonials', type: 'testimonials', label: 'Customer Reviews', enabled: true, content: { title: 'Smiles We\'ve Created' } },
      { id: 'contact', type: 'contact', label: 'Order Now', enabled: true, content: { title: 'Place a Custom Order', email: 'orders@petalandbloom.in' } },
    ],
  },
  {
    id: 'music_school',
    label: 'Music School',
    category: 'Education',
    emoji: '🎵',
    description: 'Music academies, instrument classes, and sound studios',
    suggestedThemes: ['violet', 'plum', 'midnight'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Discover the Musician Within You', subtext: 'Classical and contemporary music training for children, teens, and adults — guitar, violin, keyboard, vocals, tabla, and more in Kolkata', cta: 'Book a Free Trial Class', ctaLink: '#trial' } },
      { id: 'about', type: 'about', label: 'About the Academy', enabled: true, content: { title: 'A Decade of Musical Excellence', body: 'Raaga Music Academy was established in 2014 in Salt Lake, Kolkata by Pt. Debashish Mukherjee, a disciple of the Jaipur-Atrauli gharana. Today we have a team of 18 faculty members trained in both Indian classical and Western music, teaching over 400 students every month. Our students have performed at Doverlane Music Conference and Sangeet Natak Akademi events.', image: '' } },
      { id: 'features', type: 'features', label: 'Our Courses', enabled: true, content: { title: 'What We Teach', items: ['Hindustani Vocal & Bhajan', 'Tabla & Pakhawaj', 'Sitar, Guitar & Violin', 'Western Piano & Keyboard', 'Music Theory & Notation', 'Recording Studio Sessions', 'Online Music Classes', 'Exam Prep (Trinity & ABRSM)'] } },
      { id: 'pricing', type: 'pricing', label: 'Course Fees', enabled: true, content: { title: 'Monthly & Quarterly Fee Plans' } },
      { id: 'team', type: 'team', label: 'Our Faculty', enabled: true, content: { title: 'Meet Your Music Gurus' } },
      { id: 'stats', type: 'stats', label: 'Academy at a Glance', enabled: true, content: { stats: ['400+ Active Students', '18 Expert Faculty', '10 Instruments Taught', '10 Years of Excellence'] } },
      { id: 'testimonials', type: 'testimonials', label: 'Student & Parent Reviews', enabled: true, content: { title: 'Musical Journeys Shared' } },
      { id: 'contact', type: 'contact', label: 'Enroll Now', enabled: true, content: { title: 'Book a Free Trial Lesson', email: 'admissions@raagaacademy.in' } },
    ],
  },
  {
    id: 'pet_shop',
    label: 'Pet Shop & Vet',
    category: 'Healthcare',
    emoji: '🐾',
    description: 'Pet stores, veterinary clinics, and grooming salons',
    suggestedThemes: ['forest', 'sage', 'teal_fresh'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Because Your Pet Deserves the Best', subtext: 'Complete pet care under one roof — vet consultations, grooming, food, accessories, and boarding in Baner, Pune', cta: 'Book a Vet Visit', ctaLink: '#appointment' } },
      { id: 'about', type: 'about', label: 'About Us', enabled: true, content: { title: 'Passionate About Pets Since 2016', body: 'PawsFirst Pet Clinic & Store was founded by Dr. Sneha Joshi, BVSc, in Baner, Pune to fill the gap for a truly comprehensive neighbourhood pet care centre. We combine a well-stocked pet store with an in-house veterinary clinic and professional grooming salon — so you never have to go elsewhere for your furry family member\'s needs.', image: '' } },
      { id: 'features', type: 'features', label: 'Our Services', enabled: true, content: { title: 'Full-Spectrum Pet Care', items: ['Veterinary OPD & Vaccination', 'Spay & Neuter Surgeries', 'Pet Grooming & Spa', 'Premium Pet Food & Accessories', 'Dog Training Classes', 'Pet Boarding & Daycare', 'Dental Cleaning for Pets', 'Home Visit Consultations'] } },
      { id: 'stats', type: 'stats', label: 'Pet Care by the Numbers', enabled: true, content: { stats: ['3,000+ Pets Treated', '1 BVSc Veterinarian on Site', 'Open 7 Days a Week', '4.9★ on Google Maps'] } },
      { id: 'gallery', type: 'gallery', label: 'Happy Patients', enabled: true, content: { title: 'Our Furry Patients' } },
      { id: 'testimonials', type: 'testimonials', label: 'Pet Parent Reviews', enabled: true, content: { title: 'What Pet Parents Say' } },
      { id: 'hours', type: 'hours', label: 'Clinic Hours', enabled: true, content: { weekdays: 'Mon–Sat: 9:00 AM – 8:00 PM', weekends: 'Sunday: 10:00 AM – 5:00 PM', address: 'Shop 7, Baner Road, Near DP Road, Pune 411045', phone: '+91 98812 76543' } },
      { id: 'contact', type: 'contact', label: 'Book Appointment', enabled: true, content: { title: 'Book a Vet or Grooming Appointment', email: 'care@pawsfirstpune.in' } },
    ],
  },
  {
    id: 'startup',
    label: 'Tech Startup',
    category: 'Business',
    emoji: '💡',
    description: 'SaaS products, apps, and technology companies',
    suggestedThemes: ['midnight', 'indigo_warm', 'violet'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'The Smarter Way to Manage Your Business', subtext: 'An all-in-one SaaS platform that automates invoicing, inventory, and customer communication for Indian SMBs — free to start, scales with you', cta: 'Start Free Trial', ctaLink: '#signup' } },
      { id: 'features', type: 'features', label: 'Features', enabled: true, content: { title: 'Everything You Need to Run Your Business', items: ['GST-Ready Invoicing in Seconds', 'Inventory & Stock Management', 'WhatsApp & Email Automation', 'Payments via UPI / Razorpay', 'Customer & Vendor CRM', 'Real-Time Reports & Analytics', 'Multi-User Access & Roles', 'Works on Mobile & Desktop'] } },
      { id: 'stats', type: 'stats', label: 'Traction', enabled: true, content: { stats: ['12,000+ SMBs on Platform', '₹500 Cr+ Invoices Processed', 'Backed by Y Combinator India', '4.8★ on Product Hunt'] } },
      { id: 'pricing', type: 'pricing', label: 'Pricing', enabled: true, content: { title: 'Simple, Transparent Pricing' } },
      { id: 'testimonials', type: 'testimonials', label: 'Customer Stories', enabled: true, content: { title: 'What Our Users Say' } },
      { id: 'faq', type: 'faq', label: 'FAQ', enabled: true, content: { title: 'Common Questions About the Platform' } },
      { id: 'blog', type: 'blog', label: 'Blog', enabled: true, content: { title: 'Resources for Indian SMBs' } },
      { id: 'contact', type: 'contact', label: 'Get Started', enabled: true, content: { title: 'Talk to Sales or Get a Demo', email: 'sales@vyapaartech.in' } },
    ],
  },
  {
    id: 'spiritual',
    label: 'Spiritual & Astrology',
    category: 'Wellness',
    emoji: '🔮',
    description: 'Astrologers, tarot readers, spiritual healers',
    suggestedThemes: ['plum', 'burgundy', 'golden'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Clarity. Guidance. Peace of Mind.', subtext: 'Vedic astrology, Tarot readings, Vastu Shastra, and spiritual counselling — over 25 years of practice, 50,000+ consultations', cta: 'Book a Consultation', ctaLink: '#consult' } },
      { id: 'about', type: 'about', label: 'About the Practitioner', enabled: true, content: { title: 'Pt. Raghavendra Shastri — A Life of Spiritual Service', body: 'Born into a lineage of Jyotish practitioners in Varanasi, Pt. Raghavendra Shastri has been offering Vedic astrology and Vastu consultations since 1999. He has counselled politicians, business leaders, and ordinary families alike — always with the belief that every person has the power to shape their destiny through right action and awareness. Consultations available in Hindi, English, and Marathi.', image: '' } },
      { id: 'features', type: 'features', label: 'Services Offered', enabled: true, content: { title: 'Spiritual & Astrological Services', items: ['Kundali & Birth Chart Analysis', 'Marriage Compatibility Matching', 'Career & Business Muhurat', 'Vastu Consultation for Home & Office', 'Tarot Card Readings', 'Gemstone & Rudraksha Recommendation', 'Numerology & Name Correction', 'Puja & Ritual Arrangement'] } },
      { id: 'pricing', type: 'pricing', label: 'Consultation Fees', enabled: true, content: { title: 'Service Charges' } },
      { id: 'stats', type: 'stats', label: 'Experience', enabled: true, content: { stats: ['25+ Years of Practice', '50,000+ Consultations', 'Clients in 30+ Countries', 'Featured in Dainik Bhaskar'] } },
      { id: 'testimonials', type: 'testimonials', label: 'Client Testimonials', enabled: true, content: { title: 'Experiences Shared by Seekers' } },
      { id: 'faq', type: 'faq', label: 'FAQ', enabled: true, content: { title: 'Common Questions' } },
      { id: 'contact', type: 'contact', label: 'Book Consultation', enabled: true, content: { title: 'Schedule Your Reading', email: 'consult@shastriji.in' } },
    ],
  },
  {
    id: 'packers',
    label: 'Packers & Movers',
    category: 'Services',
    emoji: '📦',
    description: 'Logistics, packers and movers, courier services',
    suggestedThemes: ['navy', 'slate', 'ocean'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Your Move. Our Responsibility.', subtext: 'Safe, affordable, and on-time relocation services for homes and offices across India — IBA approved, fully insured, zero damage guarantee', cta: 'Get Free Quote', ctaLink: '#quote' } },
      { id: 'about', type: 'about', label: 'About Us', enabled: true, content: { title: 'India\'s Trusted Relocation Partner', body: 'SwiftMove Packers & Movers has been relocating families and businesses across India since 2009. With 12 branches from Delhi to Chennai and a fleet of 80+ GPS-tracked vehicles, we offer end-to-end packing, loading, transit, unloading, and unpacking services. IBA-approved for bank and government transfers. Every shipment is covered under a comprehensive transit insurance policy.', image: '' } },
      { id: 'features', type: 'features', label: 'Our Services', enabled: true, content: { title: 'Complete Relocation Services', items: ['Home Shifting (Local & Intercity)', 'Office & Corporate Relocation', 'Vehicle Transportation', 'Warehousing & Storage', 'International Relocation Assistance', 'Fragile & Antique Item Packing', 'Pet Relocation Services', 'Free Survey & Quotation'] } },
      { id: 'stats', type: 'stats', label: 'Our Scale', enabled: true, content: { stats: ['20,000+ Families Relocated', '80+ GPS-Tracked Vehicles', 'IBA Approved Mover', 'Pan-India Coverage'] } },
      { id: 'pricing', type: 'pricing', label: 'Moving Packages', enabled: true, content: { title: 'Transparent Moving Packages' } },
      { id: 'testimonials', type: 'testimonials', label: 'Customer Reviews', enabled: true, content: { title: 'Happy Families Speak' } },
      { id: 'faq', type: 'faq', label: 'FAQ', enabled: true, content: { title: 'Before You Move — Common Questions' } },
      { id: 'contact', type: 'contact', label: 'Get a Quote', enabled: true, content: { title: 'Get Your Free Moving Estimate', email: 'quote@swiftmoveindia.in' } },
    ],
  },
  {
    id: 'cleaning',
    label: 'Cleaning Services',
    category: 'Services',
    emoji: '🧹',
    description: 'Home cleaning, commercial cleaning, laundry services',
    suggestedThemes: ['teal_fresh', 'sage', 'ocean'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'A Spotless Home, Guaranteed.', subtext: 'Professional deep cleaning, bathroom sanitisation, kitchen scrubbing, and sofa cleaning services across Hyderabad — fully vetted staff, eco-friendly products', cta: 'Book a Cleaning', ctaLink: '#book' } },
      { id: 'about', type: 'about', label: 'About Us', enabled: true, content: { title: 'Hyderabad\'s Most Trusted Cleaning Company', body: 'ShineBright Home Services has been transforming messy homes into spotless sanctuaries across Hyderabad since 2017. All our cleaning professionals are police-verified, uniformed, and trained in our 40-hour onboarding programme. We use only non-toxic, child- and pet-safe cleaning agents — no harsh chemicals that linger in your living space.', image: '' } },
      { id: 'features', type: 'features', label: 'Our Services', enabled: true, content: { title: 'Professional Cleaning Services', items: ['Full Home Deep Cleaning', 'Bathroom & Kitchen Sanitisation', 'Sofa, Carpet & Mattress Cleaning', 'Move-In / Move-Out Cleaning', 'Office & Commercial Cleaning', 'Post-Construction Cleaning', 'Water Tank Cleaning', 'Regular Maid / Cook Services'] } },
      { id: 'pricing', type: 'pricing', label: 'Service Packages', enabled: true, content: { title: 'Cleaning Packages Starting ₹999' } },
      { id: 'stats', type: 'stats', label: 'Our Numbers', enabled: true, content: { stats: ['15,000+ Homes Cleaned', '100% Police-Verified Staff', '4.7★ on UrbanClap', '7 Years in Business'] } },
      { id: 'testimonials', type: 'testimonials', label: 'Customer Reviews', enabled: true, content: { title: 'What Homeowners Are Saying' } },
      { id: 'faq', type: 'faq', label: 'FAQ', enabled: true, content: { title: 'Common Questions About Our Services' } },
      { id: 'contact', type: 'contact', label: 'Book Now', enabled: true, content: { title: 'Schedule Your Cleaning', email: 'book@shinebrighthyd.in' } },
    ],
  },
  {
    id: 'printing',
    label: 'Printing & Stationery',
    category: 'Services',
    emoji: '🖨️',
    description: 'Print shops, branding studios, custom stationery',
    suggestedThemes: ['midnight', 'charcoal', 'slate'],
    defaultSections: [
      { id: 'hero', type: 'hero', label: 'Hero Banner', enabled: true, content: { headline: 'Print That Makes an Impression', subtext: 'Custom business cards, brochures, banners, packaging, and branded merchandise — fast turnaround, premium quality, delivered across India', cta: 'Get an Instant Quote', ctaLink: '#quote' } },
      { id: 'about', type: 'about', label: 'About Us', enabled: true, content: { title: 'Printers of Choice for 500+ Brands', body: 'InkCraft Print Studio is a full-service commercial printing company based in Ahmedabad, serving businesses across India since 2011. We operate UV, offset, and digital printing lines under one roof, enabling us to handle everything from a box of visiting cards to a 10,000-unit product packaging run — with guaranteed colour accuracy and 48-hour standard dispatch.', image: '' } },
      { id: 'features', type: 'features', label: 'What We Print', enabled: true, content: { title: 'Our Printing Services', items: ['Business Cards & Letterheads', 'Brochures, Catalogues & Flyers', 'Flex Banners & Hoardings', 'Product Packaging & Boxes', 'Branded Corporate Gifts', 'T-Shirts & Promotional Merchandise', 'Wedding Invitations & Cards', 'Stickers, Labels & Decals'] } },
      { id: 'stats', type: 'stats', label: 'Production Highlights', enabled: true, content: { stats: ['500+ Brand Clients', '48-Hour Standard Dispatch', 'UV, Offset & Digital Printing', 'Pan-India Delivery'] } },
      { id: 'pricing', type: 'pricing', label: 'Pricing', enabled: true, content: { title: 'Competitive Printing Rates' } },
      { id: 'gallery', type: 'gallery', label: 'Print Samples', enabled: true, content: { title: 'Our Work' } },
      { id: 'testimonials', type: 'testimonials', label: 'Client Reviews', enabled: true, content: { title: 'What Our Clients Say' } },
      { id: 'contact', type: 'contact', label: 'Get a Quote', enabled: true, content: { title: 'Request a Printing Quote', email: 'orders@inkcraftprint.in' } },
    ],
  },
]
